[CmdletBinding()]
param(
    [Parameter(Mandatory)][string] $ArtifactRoot,
    [Parameter(Mandatory)][string] $FfmpegPath,
    [Parameter(Mandatory)][string] $FfprobePath,
    [Parameter(Mandatory)][string] $OutputDirectory
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# This proof-only qualifier deliberately encodes new bounded outputs. It is not
# product rendering, does not select a shipping runtime, and never appends its
# evidence to retention; the primary thread retains every attempt separately.
$repositoryRoot = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..')).TrimEnd('\','/')
$approvedArtifactRoot = Join-Path ([IO.Path]::GetDirectoryName($repositoryRoot)) 'ReelForge.Gate0Artifacts'
$approvedStagingRoot = Join-Path ([IO.Path]::GetDirectoryName($repositoryRoot)) 'ReelForge.Gate0Staging'
$retentionValidator = Join-Path $PSScriptRoot 'Test-Gate0ArtifactRetention.ps1'
$helperPath = Join-Path $PSScriptRoot 'G05MarkerSurvivabilityHelpers.psm1'
Import-Module $helperPath -Force
function Hash([string]$Path) { (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToUpperInvariant() }
function Atomic([string]$Path,$Value) { $temp="$Path.partial"; try { [IO.File]::WriteAllText($temp,($Value|ConvertTo-Json -Depth 100),[Text.UTF8Encoding]::new($false)); Move-Item -LiteralPath $temp -Destination $Path -Force } finally { if(Test-Path $temp){Remove-Item $temp -Force} } }
function Assert-Root([string]$Path,[string]$Name,[bool]$MustExist=$true) { if(-not[IO.Path]::IsPathRooted($Path)){throw "$Name must be absolute."};$full=[IO.Path]::GetFullPath($Path).TrimEnd('\','/');$boundary=[IO.Path]::GetDirectoryName($repositoryRoot).TrimEnd('\','/');if(-not$full.StartsWith("$boundary\",[StringComparison]::OrdinalIgnoreCase)){throw "$Name is outside the approved project-parent trust boundary."};if($MustExist-and-not(Test-Path -LiteralPath $full -PathType Container)){throw "$Name must be an existing directory."};$ancestor=if(Test-Path $full){Get-Item -LiteralPath $full -Force}else{Get-Item -LiteralPath ([IO.Path]::GetDirectoryName($full)) -Force};while($null-ne$ancestor){if(($ancestor.Attributes-band[IO.FileAttributes]::ReparsePoint)-ne0){throw "$Name traverses a reparse-point."};if($ancestor.FullName.TrimEnd('\','/').Equals($boundary,[StringComparison]::OrdinalIgnoreCase)){break};$ancestor=$ancestor.Parent};if(Test-Path $full){foreach($item in @(Get-ChildItem -LiteralPath $full -Force -Recurse)){if(($item.Attributes-band[IO.FileAttributes]::ReparsePoint)-ne0){throw "$Name contains a reparse-point."}}};$full }
function Assert-Tool([string]$Path,[string]$Expected,[string]$ExpectedHash,[string]$Name) { if(-not[IO.Path]::IsPathRooted($Path)-or-not(Test-Path -LiteralPath $Path -PathType Leaf)){throw "$Name must be an existing absolute file."};$resolved=(Resolve-Path -LiteralPath $Path).Path;if(-not$resolved.Equals($Expected,[StringComparison]::OrdinalIgnoreCase)){throw "$Name must equal the exact approved P2 relative path; PATH discovery is prohibited."};if((Get-Item -LiteralPath $resolved -Force).Attributes-band[IO.FileAttributes]::ReparsePoint){throw "$Name is a reparse-point."};if((Hash $resolved)-ne$ExpectedHash){throw "$Name hash mismatch."};$resolved }
function Retained([string]$Relative,[object]$Expected) { if([IO.Path]::IsPathRooted($Relative)-or$Relative.Contains('..')){throw 'Unsafe retained relative path.'};if($Expected-is[Collections.IDictionary]){if(-not$Expected.Contains('size')-or-not$Expected.Contains('sha256')){throw "Retained expectation lacks explicit size/SHA properties: $Relative"};$size=$Expected['size'];$sha=$Expected['sha256']}else{if($null-eq$Expected-or$null-eq$Expected.PSObject.Properties['size']-or$null-eq$Expected.PSObject.Properties['sha256']){throw "Retained expectation lacks explicit size/SHA properties: $Relative"};$size=$Expected.size;$sha=$Expected.sha256};$path=[IO.Path]::GetFullPath((Join-Path $artifact $Relative.Replace('/','\')));if(-not$path.StartsWith("$artifact\",[StringComparison]::OrdinalIgnoreCase)-or-not(Test-Path -LiteralPath $path -PathType Leaf)){throw "Retained file missing or escaped: $Relative"};$item=Get-Item -LiteralPath $path;if($item.Length-ne[int64]$size-or(Hash $path)-ne([string]$sha).ToUpperInvariant()){throw "Retained file identity mismatch: $Relative"};$path }
function ExistingEvidence([string]$Path,[string]$RelativeDirectory) { if(Test-Path -LiteralPath $Path -PathType Leaf){$item=Get-Item -LiteralPath $Path;return [ordered]@{path="$RelativeDirectory/$([IO.Path]::GetFileName($Path))";size=$item.Length;sha256=(Hash $Path)}};$null }
function Optional([object]$Value,[string]$Name) { $property=$Value.PSObject.Properties[$Name];if($null-eq$property){$null}else{$property.Value} }
function Run([string]$Exe,[string[]]$Tokens,[string]$Name) { $stdout=Join-Path $logs "$Name.stdout.txt";$stderr=Join-Path $logs "$Name.stderr.txt";& $Exe @Tokens 1>$stdout 2>$stderr;[ordered]@{ executable=$Exe; arguments=$Tokens; exitCode=$LASTEXITCODE; stdout=[ordered]@{path="logs/$([IO.Path]::GetFileName($stdout))";size=(Get-Item $stdout).Length;sha256=(Hash $stdout)};stderr=[ordered]@{path="logs/$([IO.Path]::GetFileName($stderr))";size=(Get-Item $stderr).Length;sha256=(Hash $stderr)} } }
function Parse-DecimalInvariant([object]$Value,[string]$Label) { $number=[decimal]0;if($null-eq$Value-or-not[decimal]::TryParse([string]$Value,[Globalization.NumberStyles]::Float,[Globalization.CultureInfo]::InvariantCulture,[ref]$number)){throw "$Label is not an invariant decimal."};$number }
function NormalizedPts($Frames) { @($Frames | ForEach-Object { $value = if($null-ne$_.best_effort_timestamp_time){Parse-DecimalInvariant $_.best_effort_timestamp_time 'best_effort_timestamp_time'}elseif($null-ne$_.pts_time){Parse-DecimalInvariant $_.pts_time 'pts_time'}else{throw 'Video frame is missing presentation timestamp.'}; [int64][Math]::Round($value*1000,0,[MidpointRounding]::AwayFromZero) }) }

$out=$null;$state=[ordered]@{schemaVersion=1;proofId='Gate0.G05.MarkerSurvivability.V1';status='started';durationSeconds=30;expectedFrames=750;canvas=[ordered]@{width=1920;height=1080;frameRate='25/1';comparisonTimeBase='1/1000'};routeReencodePerformed=$true;routes=@();nonClaims=@('Proof-only P2 runtime route evidence; not current ReelForge product composition behavior.','No shipping-runtime, distribution, patent, or legal conclusion.');error=$null}
try {
    $artifact=Assert-Root $ArtifactRoot 'ArtifactRoot';if(-not$artifact.Equals($approvedArtifactRoot,[StringComparison]::OrdinalIgnoreCase)){throw "ArtifactRoot must be the exact approved repository sibling: $approvedArtifactRoot"}
    $out=Assert-Root $OutputDirectory 'OutputDirectory' $false;if([IO.Path]::GetDirectoryName($out)-ne$approvedStagingRoot){throw "OutputDirectory must be a new direct child beneath approved staging root: $approvedStagingRoot"};if(Test-Path -LiteralPath $out){throw 'OutputDirectory must be new.'};[IO.Directory]::CreateDirectory($out)|Out-Null;$logs=Join-Path $out 'logs';$mediaDirectory=Join-Path $out 'media';$stripDirectory=Join-Path $out 'marker-strips';$pcmDirectory=Join-Path $out 'decoded-audio';@($logs,$mediaDirectory,$stripDirectory,$pcmDirectory)|%{[IO.Directory]::CreateDirectory($_)|Out-Null}
    $state.localCorpusPreflight=& $retentionValidator -ArtifactRoot $artifact
    $p2='p2/runtime/ffmpeg-n8.1.2-44-g7c533d0f86-win64-lgpl-shared-8.1/bin';$ffmpeg=Assert-Tool $FfmpegPath (Join-Path $artifact "$p2/ffmpeg.exe") 'E41DBF0563AF8B07D8CF1818187500ACDF36AAAFB00186BA12A18C6C661F7EB0' 'FfmpegPath';$ffprobe=Assert-Tool $FfprobePath (Join-Path $artifact "$p2/ffprobe.exe") '08AE7637A339009A23BA469AAFC282A16A98E02B2999E14EC1A6C1198FD77221' 'FfprobePath';$runtimeManifestPath=Join-Path $PSScriptRoot 'manifests/p2-btbn-lgplv3-shared-windows-x64-20260820.json';$runtimeManifest=Get-Content $runtimeManifestPath -Raw|ConvertFrom-Json -Depth 32;$state.runtime=[ordered]@{profileId=$runtimeManifest.profileId;licensePath=$runtimeManifest.licensePath;manifest=[ordered]@{path='eng/gate0/manifests/p2-btbn-lgplv3-shared-windows-x64-20260820.json';sha256=(Hash $runtimeManifestPath)};ffmpeg=[ordered]@{path=$p2+'/ffmpeg.exe';sha256=(Hash $ffmpeg)};ffprobe=[ordered]@{path=$p2+'/ffprobe.exe';sha256=(Hash $ffprobe)}}
    $summary=Get-Content (Join-Path $PSScriptRoot 'g0.5-stage2-preparation-result-summary.json') -Raw|ConvertFrom-Json -Depth 64;$admitted=@($summary.syntheticAudioControls.admittedRoutes);$expectedRoutes=@('Video.Export.Compatibility.Mp4H264Aac.P2OpenH264','Video.Export.Open.WebmVp9Opus');if(@(Compare-Object $expectedRoutes $admitted).Count-ne0){throw 'Tracked Stage 2 result summary does not admit exactly the two required routes.'};$generator=@($summary.preparationScripts|? path -eq 'eng/gate0/Generate-G05Stage2MarkerAtlas.ps1');if($generator.Count-ne1-or(Hash (Join-Path $repositoryRoot $generator[0].path))-ne$generator[0].sha256){throw 'Marker generator hash differs from tracked Stage 2 result summary.'};$contract=@($summary.contracts|? path -eq 'eng/gate0/g0.5-stage2-workload-contract.json');if($contract.Count-ne1-or(Hash (Join-Path $repositoryRoot $contract[0].path))-ne$contract[0].sha256){throw 'Marker contract hash differs from tracked Stage 2 result summary.'}
    $expected=@{};foreach($x in @($summary.derivedTruth)){if($x.id-eq'g05-long-frame-index-atlas'){$expected['fixtures/G05/g0.5-frame-index-atlas-90000x17bit.ppm']=$x}};$expected['fixtures/F1/f1-pattern-000.ppm']=[ordered]@{size=172815;sha256='2F0A75C882C49BABF9A2B29B34DDECDCDABFFF05EF5097FF43BD91E96BC6D173'};$expected['fixtures/F1/f1-pattern-001.ppm']=[ordered]@{size=172815;sha256='A029774ED6CC9BAE85A158D822A03998D69F5BCC85114B2B0BEDD1C9B574BBDD'};$expected['fixtures/F1/f1-pattern-002.ppm']=[ordered]@{size=172815;sha256='14CCA8469D8C931B850D328E943E2CEAAA5E69476477E52325200DEA3313F3AD'};$expected['fixtures/F1/f1-sync-440hz-880hz-48000-stereo.pcm']=[ordered]@{size=23040;sha256='D6D0E575C834A0BFCF442713745EC409CC0774BF4D9356DA0B68A07D3F3F0E78'};if($expected.Count-ne5-or$expected['fixtures/G05/g0.5-frame-index-atlas-90000x17bit.ppm'].sha256-ne'BB158EA61BFD6FE99BA7ED82C6A280AE4AABE2216E87028F35002FB9EC2DFC97'){throw 'Marker contract/atlas declaration is incomplete or changed.'};$base=Retained 'fixtures/F1/f1-pattern-000.ppm' $expected['fixtures/F1/f1-pattern-000.ppm'];$baseOne=Retained 'fixtures/F1/f1-pattern-001.ppm' $expected['fixtures/F1/f1-pattern-001.ppm'];$baseTwo=Retained 'fixtures/F1/f1-pattern-002.ppm' $expected['fixtures/F1/f1-pattern-002.ppm'];$audio=Retained 'fixtures/F1/f1-sync-440hz-880hz-48000-stereo.pcm' $expected['fixtures/F1/f1-sync-440hz-880hz-48000-stereo.pcm'];$atlas=Retained 'fixtures/G05/g0.5-frame-index-atlas-90000x17bit.ppm' $expected['fixtures/G05/g0.5-frame-index-atlas-90000x17bit.ppm'];$baseSequence=Join-Path ([IO.Path]::GetDirectoryName($base)) 'f1-pattern-%03d.ppm';$state.fixtures=[ordered]@{f1VisualSequence=@('fixtures/F1/f1-pattern-000.ppm','fixtures/F1/f1-pattern-001.ppm','fixtures/F1/f1-pattern-002.ppm');f1Audio='fixtures/F1/f1-sync-440hz-880hz-48000-stereo.pcm';markerAtlas='fixtures/G05/g0.5-frame-index-atlas-90000x17bit.ppm';markerOverlay=[ordered]@{sourceCrop='17x1 indexed atlas marker';scaled='272x16 neighbor';position='x=16,y=16';bits=17;cell='16x16'}}
    $driveName=[IO.Path]::GetPathRoot($out).TrimEnd(':','\');$drive=Get-PSDrive -Name $driveName;if($null-eq$drive-or$drive.Provider.Name-ne'FileSystem'-or$null-eq$drive.Free){throw "Could not resolve filesystem free space for drive $driveName."};$free=[int64]$drive.Free;$required=[int64](2GB + (750*272*16*2) + (1440000*4*2) + (1920*1080*3));if($free-lt$required){throw "Insufficient free space: required conservative $required bytes, available $free bytes."};$state.freeSpacePreflight=[ordered]@{driveName=$driveName;availableBytes=$free;requiredBytes=$required;calculation='2 GiB fixed working reserve + two 750-frame 272x16 gray strip sets + two 30-second 48 kHz stereo s16le decodes + one 1080p rgb frame; conservative for bounded proof outputs/logs.'}
    $workload = Get-Content (Join-Path $PSScriptRoot 'g0.5-stage2-workload-contract.json') -Raw | ConvertFrom-Json -Depth 64
    $audioOraclePath=Join-Path $PSScriptRoot 'g0.5-lossy-audio-oracle-contract.json';$audioOracle=Get-Content $audioOraclePath -Raw|ConvertFrom-Json -Depth 64;if([int64]$workload.markerQualification.decodedAudio.maximumRawDecoderTailSamples-ne[int64]$audioOracle.rawAndNormalizedTiming.maximumRecordedPrimingOrDiscardPaddingSamples){throw 'Marker raw-audio tail limit differs from the frozen lossy-audio oracle.'}
    $longForm = @($workload.workloads | Where-Object id -eq 'long-form-adapter-1v1a-60m')
    if($longForm.Count-ne1-or$workload.markerQualification.videoFilterGraph-ne$longForm[0].videoFilterGraph-or$workload.markerQualification.audioFilterGraph-ne$longForm[0].audioFilterGraph){throw 'Marker qualification graphs must exactly equal the long-form workload graphs.'}
    $state.contracts=[ordered]@{workload=[ordered]@{path='eng/gate0/g0.5-stage2-workload-contract.json';sha256=(Hash (Join-Path $PSScriptRoot 'g0.5-stage2-workload-contract.json'))};lossyAudioOracle=[ordered]@{path='eng/gate0/g0.5-lossy-audio-oracle-contract.json';sha256=(Hash $audioOraclePath)};preparationSummary=[ordered]@{path='eng/gate0/g0.5-stage2-preparation-result-summary.json';sha256=(Hash (Join-Path $PSScriptRoot 'g0.5-stage2-preparation-result-summary.json'))};harness=[ordered]@{path='eng/gate0/Invoke-G05MarkerSurvivability.ps1';sha256=(Hash $PSCommandPath)};helper=[ordered]@{path='eng/gate0/G05MarkerSurvivabilityHelpers.psm1';sha256=(Hash $helperPath)}}
    $profiles = @($workload.markerQualification.requiredRouteQualityProfiles)
    if ($profiles.Count -ne 2 -or $profiles[0].routeId -ne 'mp4-openh264-aac' -or $profiles[0].qualityProfileId -ne 'openh264-constrained-baseline-2m-aaclc-192k' -or $profiles[1].routeId -ne 'webm-vp9-opus' -or $profiles[1].qualityProfileId -ne 'vp9-crf32-cpu2-opus-128k-cbr') { throw 'Marker quality profiles differ from the approved contract.' }
    $contractRoutes=@{};foreach($contractRoute in @($workload.routes)){$contractRoutes[[string]$contractRoute.id]=$contractRoute};if($contractRoutes.Count-ne2){throw 'Workload contract must define exactly two routes.'}
    $routeSpecs=@(
        [ordered]@{id=$expectedRoutes[0];contractRouteId=$profiles[0].routeId;qualityProfileId=$profiles[0].qualityProfileId;observedDescriptor=$profiles[0].observedDescriptor;extension='mp4';demuxer='mov,mp4,m4a,3gp,3g2,mj2';decoder='h264';audioDecoder='aac';contractRoute=$contractRoutes[$profiles[0].routeId]},
        [ordered]@{id=$expectedRoutes[1];contractRouteId=$profiles[1].routeId;qualityProfileId=$profiles[1].qualityProfileId;observedDescriptor=$profiles[1].observedDescriptor;extension='webm';demuxer='matroska,webm';decoder='vp9';audioDecoder='opus';contractRoute=$contractRoutes[$profiles[1].routeId]}
    )
    foreach($route in $routeSpecs){
        $name=if($route.extension-eq'mp4'){'mp4-openh264-aac'}else{'webm-vp9-opus'}
        $output=Join-Path $mediaDirectory "$name.$($route.extension)";$strip=Join-Path $stripDirectory "$name.gray";$pcm=Join-Path $pcmDirectory "$name.s16le"
        $encode=$null;$probe=$null;$packetProbe=$null;$decode=$null;$audioDecode=$null
        try {
            $filter="$($workload.markerQualification.videoFilterGraph);$($workload.markerQualification.audioFilterGraph)"
            $cr=$route.contractRoute;$encodeTokens=@('-v','error','-filter_threads','1','-filter_complex_threads','1','-stream_loop','-1','-framerate','25','-f','image2','-c:v','ppm','-threads:v','1','-i',$baseSequence,'-loop','1','-framerate','25','-f','image2','-c:v','ppm','-threads:v','1','-i',$atlas,'-stream_loop','-1','-f','s16le','-c:a','pcm_s16le','-ar','48000','-ac','2','-threads:a','1','-i',$audio,'-filter_complex',$filter,'-map','[vout]','-map','[aout]','-frames:v','750','-t','30','-c:v',$cr.videoEncoder,'-threads:v:0','1')+@($cr.videoOptions)+@('-c:a',$cr.audioEncoder,'-threads:a:0','1')+@($cr.audioOptions)+@($cr.muxerOptions)+@('-f',$cr.muxer,'-y',$output)
            $encode=Run $ffmpeg $encodeTokens "encode-$name";if($encode.exitCode-ne0){throw "Encode failed for $name."}
            $probe=Run $ffprobe @('-v','error','-f',$route.demuxer,'-show_streams','-show_frames','-show_format','-of','json',$output) "probe-$name";if($probe.exitCode-ne0){throw "Probe failed for $name."}
            $probeJson=Get-Content (Join-Path $logs "probe-$name.stdout.txt") -Raw|ConvertFrom-Json;$video=@($probeJson.streams|? codec_type -eq 'video');$audioStream=@($probeJson.streams|? codec_type -eq 'audio')
            $packetProbe=Run $ffprobe @('-v','error','-f',$route.demuxer,'-show_packets','-of','json',$output) "probe-packets-$name";if($packetProbe.exitCode-ne0){throw "Packet probe failed for $name."};$packetJson=Get-Content (Join-Path $logs "probe-packets-$name.stdout.txt") -Raw|ConvertFrom-Json
            if($video.Count-ne1-or$audioStream.Count-ne1){throw "Explicit stream identity gate failed for $name."}
            $expected=$route.observedDescriptor;$observed=[ordered]@{formatName=$probeJson.format.format_name;videoCodec=$video[0].codec_name;videoProfile=$video[0].profile;pixelFormat=$video[0].pix_fmt;width=$video[0].width;height=$video[0].height;rFrameRate=$video[0].r_frame_rate;avgFrameRate=$video[0].avg_frame_rate;audioCodec=$audioStream[0].codec_name;audioProfile=(Optional $audioStream[0] 'profile');audioSampleRate=[int]$audioStream[0].sample_rate;audioChannels=[int]$audioStream[0].channels;audioChannelLayout=$audioStream[0].channel_layout}
            $criteria=[ordered]@{formatName=($observed.formatName-eq$expected.formatName);exactlyOneVideo=($video.Count-eq1);exactlyOneAudio=($audioStream.Count-eq1);videoCodec=($observed.videoCodec-eq$expected.videoCodec);videoProfile=($observed.videoProfile-eq$expected.videoProfile);pixelFormat=($observed.pixelFormat-eq$expected.pixelFormat);width=($observed.width-eq$expected.width);height=($observed.height-eq$expected.height);rFrameRate=($observed.rFrameRate-eq$expected.frameRate);avgFrameRate=($observed.avgFrameRate-eq$expected.frameRate);audioCodec=($observed.audioCodec-eq$expected.audioCodec);audioProfile=if($null-eq$expected.audioProfile){$true}else{$observed.audioProfile-eq$expected.audioProfile};audioSampleRate=($observed.audioSampleRate-eq$expected.audioSampleRate);audioChannels=($observed.audioChannels-eq$expected.audioChannels);audioChannelLayout=($observed.audioChannelLayout-eq$expected.audioChannelLayout)}
            $descriptor=[ordered]@{expected=$expected;observed=$observed;criteria=$criteria;passed=(-not(@($criteria.Values|?{$_-eq$false}).Count))};$semanticFailures=[Collections.Generic.List[string]]::new();if(-not$descriptor.passed){$semanticFailures.Add('observed-descriptor-mismatch')}
            $frames=@($probeJson.frames|? media_type -eq 'video');$decode=Run $ffmpeg @('-xerror','-v','error','-f',$route.demuxer,'-c:v',$route.decoder,'-threads:v','1','-i',$output,'-map','0:v:0','-an','-vf','crop=272:16:16:16,format=gray','-c:v','rawvideo','-f','rawvideo','-y',$strip) "decode-$name";if($decode.exitCode-ne0){throw "Marker decode failed for $name."}
            $audioDecode=Run $ffmpeg @('-xerror','-v','error','-f',$route.demuxer,'-c:a',$route.audioDecoder,'-threads:a','1','-i',$output,'-map','0:a:0','-vn','-c:a','pcm_s16le','-f','s16le','-y',$pcm) "decode-audio-$name";if($audioDecode.exitCode-ne0){throw "Audio decode failed for $name."}
            $bytes=[IO.File]::ReadAllBytes($strip);$audioBytes=[IO.File]::ReadAllBytes($pcm);$audioFrames=@($probeJson.frames|? media_type -eq 'audio');$audioPackets=@($packetJson.packets|? codec_type -eq 'audio');$audioTiming=Get-G05DecodedAudioTiming -RawByteLength $audioBytes.Length -AudioStream $audioStream[0] -AudioFrames $audioFrames -AudioPackets $audioPackets -ExpectedSamplesPerChannel ([int64]$workload.markerQualification.decodedAudio.expectedPresentationSamplesPerChannel) -MaximumRawTailSamples ([int64]$workload.markerQualification.decodedAudio.maximumRawDecoderTailSamples);if(-not$audioTiming.passed){foreach($failure in $audioTiming.failures){$semanticFailures.Add([string]$failure)}};$oracle=Get-G05MarkerDecode -Bytes $bytes -ExpectedFrames 750 -FramePts (NormalizedPts $frames)
            $aligned=($bytes.Length%(272*16)-eq0);$immediateNoExtra=($decode.exitCode-eq0-and$aligned-and$oracle.decodedFrames-eq750-and$oracle.probeFrames-eq750)
            $routePassed=($oracle.passed-and$semanticFailures.Count-eq0);$state.routes+=,[ordered]@{routeId=$route.id;contractRouteId=$route.contractRouteId;qualityProfileId=$route.qualityProfileId;status=if($routePassed){'passed'}else{'failed'};failureKind=if($routePassed){$null}else{'semantic'};semanticFailures=@($semanticFailures);routeReencodePerformed=$true;selectedComponents=[ordered]@{containerDemuxer=$route.demuxer;videoDecoder=$route.decoder;executedAudioDecoder=$route.audioDecoder;videoEncoder=$cr.videoEncoder;audioEncoder=$cr.audioEncoder;muxer=$cr.muxer;filters=@('crop','scale','overlay','format','setpts','aformat','asetpts');threads=1};encode=$encode;probe=$probe;packetProbe=$packetProbe;decode=$decode;audioDecode=$audioDecode;descriptor=$descriptor;decoderBehavior=[ordered]@{decodeExitCode=$decode.exitCode;stripBytes=$bytes.Length;stripFrameAligned=$aligned;decodedFrames=$oracle.decodedFrames;probeFrames=$oracle.probeFrames;immediateNoExtraFrameConclusion=$immediateNoExtra};media=[ordered]@{path="media/$([IO.Path]::GetFileName($output))";size=(Get-Item $output).Length;sha256=(Hash $output)};markerStrip=[ordered]@{path="marker-strips/$([IO.Path]::GetFileName($strip))";size=(Get-Item $strip).Length;sha256=(Hash $strip)};decodedAudio=[ordered]@{path="decoded-audio/$([IO.Path]::GetFileName($pcm))";size=$audioBytes.Length;sha256=(Hash $pcm);timing=$audioTiming};oracle=$oracle}
        } catch {
            $state.routes+=,[ordered]@{routeId=$route.id;contractRouteId=$route.contractRouteId;qualityProfileId=$route.qualityProfileId;status='failed';failureKind='infrastructure';routeReencodePerformed=$true;error=$_.Exception.ToString();commands=[ordered]@{encode=$encode;probe=$probe;packetProbe=$packetProbe;decode=$decode;audioDecode=$audioDecode};partialMedia=(ExistingEvidence $output 'media');partialMarkerStrip=(ExistingEvidence $strip 'marker-strips');partialDecodedAudio=(ExistingEvidence $pcm 'decoded-audio')}
        }
    }
    $state.status=if(@($state.routes|? failureKind -eq 'infrastructure').Count){'infrastructure-failed'}elseif($state.routes.Count-eq2-and@($state.routes|? status -eq 'passed').Count-eq2){'completed'}else{'completed-with-failures'}
} catch { $state.status='infrastructure-failed';$state.error=$_.Exception.ToString() } finally { if($out-and(Test-Path -LiteralPath $out)){Atomic (Join-Path $out 'g0.5-marker-survivability-report.json') $state};$state|ConvertTo-Json -Depth 100;if($state.status-ne'completed'){exit 1} }
