[CmdletBinding()]
param(
    [Parameter(Mandatory)][string]$RuntimeRoot,
    [Parameter(Mandatory)][string]$SourceEvidencePath,
    [Parameter(Mandatory)][string]$OutputDirectory
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# This is proof infrastructure for independent-playback observation. It never
# re-encodes media and a blocked derivation is recorded rather than repaired.
function Require-OutsideRepositoryEmptyDirectory([string]$Path) {
    if (-not [IO.Path]::IsPathRooted($Path)) { throw 'OutputDirectory must be an explicit rooted path outside the repository.' }
    $repository=(Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path.TrimEnd('\','/')
    $full=[IO.Path]::GetFullPath($Path).TrimEnd('\','/')
    if($full.Equals($repository,[StringComparison]::OrdinalIgnoreCase) -or $full.StartsWith("$repository\",[StringComparison]::OrdinalIgnoreCase)){throw 'OutputDirectory must be outside the repository.'}
    $ancestor=$full;while(-not(Test-Path -LiteralPath $ancestor)){$parent=Split-Path -Parent $ancestor;if(!$parent -or $parent -eq $ancestor){throw 'OutputDirectory has no existing ancestor.'};$ancestor=$parent}
    while($true){$item=Get-Item -LiteralPath $ancestor -Force;if(($item.Attributes -band [IO.FileAttributes]::ReparsePoint)-ne 0){throw "OutputDirectory ancestor is a reparse-point: $ancestor"};$parent=Split-Path -Parent $ancestor;if(!$parent -or $parent -eq $ancestor){break};$ancestor=$parent}
    if(Test-Path -LiteralPath $full){if(-not(Test-Path -LiteralPath $full -PathType Container) -or (Get-ChildItem -LiteralPath $full -Force|Select-Object -First 1)){throw 'OutputDirectory must be new or empty so playback evidence cannot include stale files.'}}else{New-Item -ItemType Directory -Path $full|Out-Null};return $full
}
function Assert-RootedFile([string]$Path,[string]$Name){if(-not [IO.Path]::IsPathRooted($Path)-or-not(Test-Path -LiteralPath $Path -PathType Leaf)){throw "$Name must be an existing explicit rooted file."};$resolved=(Resolve-Path -LiteralPath $Path).Path;$node=Split-Path -Parent $resolved;while($true){$item=Get-Item -LiteralPath $node -Force;if(($item.Attributes-band [IO.FileAttributes]::ReparsePoint)-ne 0){throw "$Name or its ancestor is a reparse-point: $node"};$parent=Split-Path -Parent $node;if(!$parent-or $parent -eq $node){break};$node=$parent};return $resolved}
function Artifact([string]$Path,[string]$Root){$item=Get-Item -LiteralPath $Path;return [ordered]@{path=([IO.Path]::GetRelativePath($Root,$Path).Replace('\','/'));length=$item.Length;sha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToUpperInvariant()}}
function Write-Utf8Json([string]$Path,[object]$Value,[int]$Depth=40){[IO.File]::WriteAllText($Path,($Value|ConvertTo-Json -Depth $Depth),[Text.UTF8Encoding]::new($false))}
function Invoke-Recorded([string]$Tool,[string[]]$Arguments,[string]$Name){$stdout=Join-Path $logs "$Name.stdout.txt";$stderr=Join-Path $logs "$Name.stderr.txt";& $Tool @Arguments 1>$stdout 2>$stderr;$record=[ordered]@{step=$Name;executable=$Tool;arguments=$Arguments;exitCode=$LASTEXITCODE;stdout=(Get-Content $stdout -Raw);stderr=(Get-Content $stderr -Raw);stdoutArtifact=(Artifact $stdout $output);stderrArtifact=(Artifact $stderr $output)};$commands.Add($record);if($LASTEXITCODE-ne 0){throw "Step '$Name' failed with exit code $LASTEXITCODE."};return $record}
function Assert-CleanLog([object]$Record,[string]$Label){$combined=([string]$Record.stdout)+"`n"+([string]$Record.stderr);if($combined -match '(?im)\b(timestamp discontinuity|non-monoton(?:ic|ous)|changing to|packet corrupt|DTS .* out of order|invalid, dropping)\b'){throw "$Label emitted timestamp repair, non-monotonic, corrupt-packet, or discontinuity evidence; this route is blocked rather than repaired."}}
function Resolve-Source([object]$Evidence,[string]$CapabilityId){$proof=@($Evidence.semanticProofs|Where-Object capabilityId -eq $CapabilityId);if($proof.Count-ne 1-or $proof[0].status-ne 'passed' -or -not $proof[0].executedSemanticProof){throw "Required source capability is missing or did not pass: $CapabilityId"};$a=$proof[0].details.artifact;if($null-eq $a-or [string]::IsNullOrWhiteSpace($a.path)){throw "Required source artifact is absent: $CapabilityId"};$relative=[string]$a.path;if([IO.Path]::IsPathRooted($relative)-or $relative.Contains('..')){throw "Source evidence contains an unsafe artifact path: $CapabilityId"};$candidate=[IO.Path]::GetFullPath((Join-Path $sourceRoot $relative));if(-not $candidate.StartsWith("$sourceRoot\",[StringComparison]::OrdinalIgnoreCase)){throw "Source artifact is outside source evidence root: $CapabilityId"};if(-not(Test-Path -LiteralPath $candidate -PathType Leaf)){throw "Source artifact is missing: $CapabilityId"};$actual=Get-Item -LiteralPath $candidate;if($actual.Length-ne [int64]$a.length-or (Get-FileHash -LiteralPath $candidate -Algorithm SHA256).Hash.ToUpperInvariant()-ne ([string]$a.sha256).ToUpperInvariant()){throw "Source artifact hash or length mismatch: $CapabilityId"};return [ordered]@{capabilityId=$CapabilityId;path=$candidate;sourceArtifact=$a}}
function Assert-SourceClosure([object]$Evidence){
    if($Evidence.schemaVersion-ne 1-or $Evidence.profileId-ne 'P2.BtbnLgplShared.WindowsX64.20260820' -or $Evidence.contract-ne 'eng/gate0/g0.4-delivery-proof-contract.json' -or $Evidence.runtimeIdentityEvidence-ne 'runtime-identity.json' -or $Evidence.preflight.status-ne 'passed' -or $null-eq $Evidence.finalArtifacts){throw 'Source evidence does not bind the approved P2 G0.4 schema, passed preflight, contract, runtime identity, and artifacts.'}
    $requiredIds=@('Video.Export.Compatibility.Mp4H264Aac.P2OpenH264','Video.Export.Compatibility.Mp4H264VideoOnly.P2OpenH264','Video.Export.Open.WebmVp9Opus','Video.Export.Open.WebmVp9VideoOnly','Audio.Export.M4aAac','Audio.Export.Mp3','Audio.Export.OggOpus','Audio.Export.WavPcm','Audio.Export.Flac','Image.Export.Png','Image.Export.Jpeg');$actualIds=@($Evidence.semanticProofs|ForEach-Object capabilityId|Sort-Object);if(@($Evidence.semanticProofs).Count-ne 11-or @($Evidence.semanticProofs|Where-Object {$_.status -eq 'passed' -and $_.executedSemanticProof}).Count-ne 11-or (@(Compare-Object $requiredIds $actualIds).Count-ne 0)){throw 'Source evidence must be the exact complete eleven-pass P2 G0.4 proof.'}
    foreach($entry in @($Evidence.finalArtifacts)){if([IO.Path]::IsPathRooted([string]$entry.path)-or ([string]$entry.path).Contains('..')){throw 'Source final artifact list contains an unsafe path.'};$candidate=[IO.Path]::GetFullPath((Join-Path $sourceRoot ([string]$entry.path)));if(-not $candidate.StartsWith("$sourceRoot\",[StringComparison]::OrdinalIgnoreCase)-or-not(Test-Path -LiteralPath $candidate -PathType Leaf)){throw 'Source final artifact is absent or outside its evidence root.'};$item=Get-Item -LiteralPath $candidate;if($item.Length-ne [int64]$entry.length-or (Get-FileHash -LiteralPath $candidate -Algorithm SHA256).Hash.ToUpperInvariant()-ne ([string]$entry.sha256).ToUpperInvariant()){throw 'Source final artifact hash closure failed.'}}
    $sourceRuntimeIdentity=Assert-RootedFile (Join-Path $sourceRoot 'runtime-identity.json') 'Source runtime identity';try{$script:sourceRuntime=Get-Content -LiteralPath $sourceRuntimeIdentity -Raw|ConvertFrom-Json}catch{throw 'Source runtime identity is invalid JSON.'};if($sourceRuntime.profileId-ne $Evidence.profileId -or [string]::IsNullOrWhiteSpace($sourceRuntime.observation.PrimaryTool.Sha256)){throw 'Source runtime identity does not identify the approved P2 primary tool.'};return $sourceRuntimeIdentity
}
function Copy-ExactTsSegment([string]$Segment,[string]$Combined,[int]$Count){$bytes=[IO.File]::ReadAllBytes($Segment);if($bytes.Length-le 0){throw 'MPEG-TS segment is empty.'};$stream=[IO.File]::Open($Combined,[IO.FileMode]::CreateNew,[IO.FileAccess]::Write,[IO.FileShare]::None);try{1..$Count|ForEach-Object{$stream.Write($bytes,0,$bytes.Length)}}finally{$stream.Dispose()};$expected=[int64]$bytes.Length*$Count;if((Get-Item -LiteralPath $Combined).Length-ne $expected){throw 'Exact MPEG-TS byte repetition length oracle failed.'};return [ordered]@{repeatCount=$Count;segment=(Artifact $Segment $output);combined=(Artifact $Combined $output);exactByteRepetition=$true}}
function Get-FormatDuration([string]$Path,[string]$Name){$record=Invoke-Recorded $probe @('-v','error','-show_packets','-show_format','-show_streams','-of','json',$Path) "source-duration-$Name";$p=$record.stdout|ConvertFrom-Json;$d=[double]$p.format.duration;if($d -le 0){throw "Source segment duration is not positive: $Name"};return [ordered]@{seconds=$d;probe=$p}}
function Assert-PacketTiming([string]$Path,[string]$Name,[string]$VideoCodec,[string]$AudioCodec,[bool]$VideoOnly,[double]$ExpectedSeconds,[object]$SourceProbe,[int]$RepeatCount){
    $record=Invoke-Recorded $probe @('-v','error','-count_packets','-show_packets','-show_streams','-show_format','-of','json',$Path) "packet-oracle-$Name";$p=$record.stdout|ConvertFrom-Json;$streams=@($p.streams);$video=@($streams|Where-Object {$_.codec_type -eq 'video'});$audio=@($streams|Where-Object {$_.codec_type -eq 'audio'});if($video.Count-ne 1-or $audio.Count-ne $(if($VideoOnly){0}else{1}) -or $video[0].codec_name-ne $VideoCodec -or ($audio.Count -eq 1 -and $audio[0].codec_name-ne $AudioCodec)){throw "$Name stream-count/codec oracle failed."};if([int]$video[0].width-ne 320-or [int]$video[0].height-ne 180-or [int]$video[0].has_b_frames-ne 0){throw "$Name video geometry or B-frame-free oracle failed."};$packets=@($p.packets);$videoIndex=[int]$video[0].index;$videoPackets=@($packets|Where-Object {[int]$_.stream_index -eq $videoIndex});if($videoPackets.Count-ne 120){throw "$Name expected exactly 120 video packets, observed $($videoPackets.Count)."};foreach($stream in @($video+$audio)){$streamIndex=[int]$stream.index;$streamPackets=@($packets|Where-Object {[int]$_.stream_index -eq $streamIndex});if($streamPackets.Count-eq 0){throw "$Name stream $($stream.index) has no packets."};$lastDts=$null;$lastPts=$null;foreach($packet in $streamPackets){if($null-eq $packet.dts-or $null-eq $packet.pts){throw "$Name stream $($stream.index) has a packet without DTS or PTS."};$dts=[int64]$packet.dts;$pts=[int64]$packet.pts;if($null-ne $lastDts -and $dts-le $lastDts){throw "$Name stream $($stream.index) DTS is not strictly monotonic."};if($null-ne $lastPts -and $pts-lt $lastPts){throw "$Name stream $($stream.index) PTS is not nondecreasing."};$lastDts=$dts;$lastPts=$pts}}
    $audioCoverage=$null
    if(-not $VideoOnly){
        $sourceAudio=@($SourceProbe.streams|Where-Object {$_.codec_type -eq 'audio'});if($sourceAudio.Count-ne 1){throw "$Name source audio-stream oracle failed."}
        $sourceAudioPackets=@($SourceProbe.packets|Where-Object {[int]$_.stream_index -eq [int]$sourceAudio[0].index});$derivedAudioPackets=@($packets|Where-Object {[int]$_.stream_index -eq [int]$audio[0].index});$expectedAudioPackets=$sourceAudioPackets.Count*$RepeatCount
        if($sourceAudioPackets.Count-eq 0-or $derivedAudioPackets.Count-ne $expectedAudioPackets){throw "$Name expected exactly $expectedAudioPackets audio packets from $($sourceAudioPackets.Count) source packets x $RepeatCount, observed $($derivedAudioPackets.Count)."}
        $lastAudio=$derivedAudioPackets[-1];if($null-eq $lastAudio.pts_time-or $null-eq $lastAudio.duration_time){throw "$Name final audio packet lacks presentation timing."};$terminal=[double]$lastAudio.pts_time+[double]$lastAudio.duration_time;$terminalTolerance=0.030;if([math]::Abs($terminal-$ExpectedSeconds)-gt $terminalTolerance){throw "$Name audio terminal timestamp oracle failed: expected $ExpectedSeconds seconds +/- $terminalTolerance seconds, observed $terminal."}
        $audioCoverage=[ordered]@{sourcePacketCount=$sourceAudioPackets.Count;repeatCount=$RepeatCount;expectedPacketCount=$expectedAudioPackets;observedPacketCount=$derivedAudioPackets.Count;expectedTerminalSeconds=$ExpectedSeconds;observedTerminalSeconds=$terminal;terminalToleranceSeconds=$terminalTolerance}
    }
    $observed=[double]$p.format.duration;$tolerance=0.150;if([math]::Abs($observed-$ExpectedSeconds)-gt $tolerance){throw "$Name duration oracle failed: expected $ExpectedSeconds seconds +/- $tolerance seconds, observed $observed."};return [ordered]@{expectedDurationSeconds=$ExpectedSeconds;durationToleranceSeconds=$tolerance;observedDurationSeconds=$observed;expectedVideoPackets=120;observedVideoPackets=$videoPackets.Count;audioCoverage=$audioCoverage;dtsPolicy='strictly increasing per stream';ptsPolicy='nondecreasing per stream; source video is B-frame-free';streamMap=@($streams|ForEach-Object{"$($_.index):$($_.codec_type):$($_.codec_name)"});probe=$p}
}
function Remove-Partial([string]$Path){if(Test-Path -LiteralPath $Path){Remove-Item -LiteralPath $Path -Force}}

$output=Require-OutsideRepositoryEmptyDirectory $OutputDirectory
$preflight=[ordered]@{status='started';failure=$null};$commands=[Collections.Generic.List[object]]::new();$routesResult=[Collections.Generic.List[object]]::new();$evidencePath=$null
trap {$preflight.status='failed';$preflight.failure=$_.Exception.Message;if($output){Write-Utf8Json (Join-Path $output 'g0.4-playback-corpus-evidence.json') ([ordered]@{schemaVersion=2;preflight=$preflight;commands=$commands;routes=$routesResult;limitations='Playback-only corpus preparation; no playback verdict.'})};throw}

$evidencePath=Assert-RootedFile $SourceEvidencePath 'SourceEvidencePath';$sourceRoot=(Split-Path -Parent $evidencePath);try{$sourceEvidence=Get-Content -LiteralPath $evidencePath -Raw|ConvertFrom-Json}catch{throw 'SourceEvidencePath is not valid JSON.'};$sourceRuntimeIdentity=Assert-SourceClosure $sourceEvidence
$runtimeRootResolved=(Resolve-Path -LiteralPath $RuntimeRoot).Path;$runtime=Assert-RootedFile (Join-Path $runtimeRootResolved 'bin\ffmpeg.exe') 'P2 ffmpeg';$probe=Assert-RootedFile (Join-Path $runtimeRootResolved 'bin\ffprobe.exe') 'P2 ffprobe'
$media=Join-Path $output 'media';$concat=Join-Path $output 'concat';$transformations=Join-Path $output 'transformations';$logs=Join-Path $output 'logs';New-Item -ItemType Directory -Path $media,$concat,$transformations,$logs|Out-Null
$runtimeEvidence=Join-Path $output 'runtime-identity.json';& (Join-Path $PSScriptRoot 'Validate-P2Runtime.ps1') -RuntimeRoot $runtimeRootResolved -EvidencePath $runtimeEvidence;if($LASTEXITCODE-ne 0){throw 'Approved P2 runtime validation failed.'};$runtimeIdentity=Get-Content -LiteralPath $runtimeEvidence -Raw|ConvertFrom-Json;if(([string]$runtimeIdentity.observation.PrimaryTool.Sha256).ToUpperInvariant() -ne ([string]$sourceRuntime.observation.PrimaryTool.Sha256).ToUpperInvariant()){throw 'Runtime primary-tool hash differs from the exact P2 G0.4 source evidence runtime.'}
$preflight.status='passed'

$routes=@(
    [ordered]@{id='Video.Export.Compatibility.Mp4H264Aac.P2OpenH264';name='h264-aac.mp4';container='mp4';mime='video/mp4';videoCodec='h264';audioCodec='aac';videoOnly=$false;method='mpegts-exact-byte-repetition'},
    [ordered]@{id='Video.Export.Compatibility.Mp4H264VideoOnly.P2OpenH264';name='h264-video-only.mp4';container='mp4';mime='video/mp4';videoCodec='h264';audioCodec='';videoOnly=$true;method='mpegts-exact-byte-repetition'},
    [ordered]@{id='Video.Export.Open.WebmVp9Opus';name='vp9-opus.webm';container='webm';mime='video/webm';videoCodec='vp9';audioCodec='opus';videoOnly=$false;method='concat-demuxer-stream-copy'},
    [ordered]@{id='Video.Export.Open.WebmVp9VideoOnly';name='vp9-video-only.webm';container='webm';mime='video/webm';videoCodec='vp9';audioCodec='';videoOnly=$true;method='concat-demuxer-stream-copy'}
)
foreach($route in $routes){
    $source=Resolve-Source $sourceEvidence $route.id;$result=[ordered]@{id=$route.id;name=$route.name;mime=$route.mime;videoOnly=[bool]$route.videoOnly;method=$route.method;repeatCount=40;source=$source.sourceArtifact;status='started';blockReason=$null;artifact=$null;timing=$null;transformation=$null}
    try {
        $segmentDuration=Get-FormatDuration $source.path $route.name;$expectedDuration=[double]$segmentDuration.seconds*40;$final=Join-Path $media $route.name;$partial=Join-Path $media ('.partial-'+$route.name)
        if($route.container -eq 'mp4'){
            $segment=Join-Path $concat ($route.name+'.segment.ts');$combined=Join-Path $concat ($route.name+'.x40.ts');$convert=Invoke-Recorded $runtime @('-hide_banner','-i',$source.path,'-map','0','-c','copy','-bsf:v','h264_mp4toannexb','-f','mpegts','-y',$segment) ('mp4-to-ts-'+$route.name);Assert-CleanLog $convert ('MP4 to MPEG-TS '+$route.name);$byteEvidence=Copy-ExactTsSegment $segment $combined 40;$remux=Invoke-Recorded $runtime @('-hide_banner','-f','mpegts','-i',$combined,'-map','0','-c','copy','-movflags','+faststart','-f','mp4','-y',$partial) ('ts-to-mp4-'+$route.name);Assert-CleanLog $remux ('MPEG-TS to MP4 '+$route.name);$transform=[ordered]@{description='Stream-copy source MP4 to MPEG-TS with explicit h264_mp4toannexb, concatenate the exact MPEG-TS segment bytes 40 times, then stream-copy remux to MP4. No decoder, encoder, filter, timestamp repair, or non-monotonic output is accepted.';input=$source.sourceArtifact;segmentDuration=$segmentDuration.seconds;expectedDurationSeconds=$expectedDuration;byteRepetition=$byteEvidence;commands=@($convert.step,$remux.step)}
        } else {
            $list=Join-Path $concat ($route.name+'.ffconcat');$escaped=$source.path.Replace("'","'\\''");[IO.File]::WriteAllLines($list,@(1..40|ForEach-Object{"file '$escaped'"}),[Text.UTF8Encoding]::new($false));$concatRecord=Invoke-Recorded $runtime @('-hide_banner','-f','concat','-safe','0','-i',$list,'-map','0','-c','copy','-f','webm','-y',$partial) ('webm-concat-'+$route.name);Assert-CleanLog $concatRecord ('WebM concat '+$route.name);$transform=[ordered]@{description='Concat-demuxer stream copy of the exact already-proven WebM source 40 times. No decoder, encoder, filter, timestamp repair, or non-monotonic output is accepted.';input=$source.sourceArtifact;segmentDuration=$segmentDuration.seconds;expectedDurationSeconds=$expectedDuration;concatList=(Artifact $list $output);commands=@($concatRecord.step)}
        }
        if(-not(Test-Path -LiteralPath $partial)-or (Get-Item -LiteralPath $partial).Length-le 0){throw "Derived corpus artifact is empty: $($route.name)"};$timing=Assert-PacketTiming $partial $route.name $route.videoCodec $route.audioCodec $route.videoOnly $expectedDuration $segmentDuration.probe 40;Move-Item -LiteralPath $partial -Destination $final;$transformPath=Join-Path $transformations ($route.name+'.json');Write-Utf8Json $transformPath $transform;$result.status='passed';$result.artifact=Artifact $final $output;$result.timing=$timing;$result.transformation=Artifact $transformPath $output
    } catch {
        $result.status='blocked';$result.blockReason=$_.Exception.Message;Remove-Partial (Join-Path $media ('.partial-'+$route.name));$blockPath=Join-Path $transformations ($route.name+'.blocked.json');Write-Utf8Json $blockPath ([ordered]@{route=$route.id;status='blocked';reason=$result.blockReason;method=$route.method;prohibition='Do not repair timestamps, re-encode, weaken packet timing oracles, or silently substitute another route.'});$result.transformation=Artifact $blockPath $output
    }
    $routesResult.Add($result)
}
$index=Join-Path $output 'index.html';Copy-Item -LiteralPath (Join-Path $PSScriptRoot 'G04PlaybackHarness.html') -Destination $index
$passed=@($routesResult|Where-Object status -eq 'passed');$blocked=@($routesResult|Where-Object status -eq 'blocked');$manifest=[ordered]@{schemaVersion=2;kind='ReelForge Gate 0 independent-playback manual harness corpus';dispositionSummary=[ordered]@{availableRouteCount=$passed.Count;blockedRouteCount=$blocked.Count};routes=@($passed|ForEach-Object{[ordered]@{id=$_.id;url=$_.artifact.path;mime=$_.mime;videoOnly=$_.videoOnly;sha256=$_.artifact.sha256;length=$_.artifact.length}});blockedRoutes=@($blocked|ForEach-Object{[ordered]@{id=$_.id;status='blocked';reason=$_.blockReason;transformation=$_.transformation}});limitations='Manual native HTMLMediaElement evidence only; no audible or perceptual sync conclusion. A blocked corpus route is unavailable and is not silently substituted.'};$manifestPath=Join-Path $output 'manifest.json';Write-Utf8Json $manifestPath $manifest
$boundArtifacts=@(Get-ChildItem -LiteralPath $output -File -Recurse -Force|Where-Object {$_.Name -notin @('g0.4-playback-corpus-evidence.json','manifest.json')}|Sort-Object FullName|ForEach-Object{Artifact $_.FullName $output})
$record=[ordered]@{schemaVersion=2;profileId=$sourceEvidence.profileId;preflight=$preflight;sourceEvidence=[ordered]@{path=$evidencePath;sha256=(Get-FileHash $evidencePath -Algorithm SHA256).Hash.ToUpperInvariant();runtimeIdentity=(Artifact $sourceRuntimeIdentity $sourceRoot)};runtimeIdentityEvidence=(Artifact $runtimeEvidence $output);sourceRuntimePrimaryToolSha256=$sourceRuntime.observation.PrimaryTool.Sha256;commands=$commands;routes=$routesResult;manifest=(Artifact $manifestPath $output);indexHtml=(Artifact $index $output);boundArtifacts=$boundArtifacts;result='completed-with-blocked-routes when a route cannot satisfy the approved no-repair timing policy';limitations='Playback-only derived corpus. It is not a new delivery-capability verdict, quality result, independent-playback verdict, shipping/runtime selection, or legal conclusion.'};Write-Utf8Json (Join-Path $output 'g0.4-playback-corpus-evidence.json') $record
