[CmdletBinding()]
param(
    [Parameter(Mandatory)][string]$RuntimeRoot,
    [Parameter(Mandatory)][string]$FixtureRoot,
    [Parameter(Mandatory)][string]$OutputDirectory
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# Gate 0 proof infrastructure only. Passing evidence does not select a shipping
# runtime or establish redistribution, patent, legal, independent-playback, or
# long-form conclusions.
function Require-OutsideRepositoryEmptyDirectory([string]$Path) {
    if (-not [IO.Path]::IsPathRooted($Path)) { throw 'OutputDirectory must be an explicit rooted path outside the repository.' }
    $repository = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path.TrimEnd('\', '/')
    $full = [IO.Path]::GetFullPath($Path).TrimEnd('\', '/')
    if ($full.Equals($repository, [StringComparison]::OrdinalIgnoreCase) -or $full.StartsWith("$repository\", [StringComparison]::OrdinalIgnoreCase)) { throw 'OutputDirectory must be outside the repository.' }
    $ancestor=$full; while(-not(Test-Path -LiteralPath $ancestor)){ $parent=Split-Path -Parent $ancestor; if([string]::IsNullOrWhiteSpace($parent) -or $parent -eq $ancestor){throw "OutputDirectory has no resolvable existing ancestor: $full"}; $ancestor=$parent }
    while($true){$item=Get-Item -LiteralPath $ancestor -Force;if(($item.Attributes -band [IO.FileAttributes]::ReparsePoint) -ne 0){throw "OutputDirectory ancestor is a reparse-point: $ancestor"};$parent=Split-Path -Parent $ancestor;if([string]::IsNullOrWhiteSpace($parent) -or $parent -eq $ancestor){break};$ancestor=$parent}
    if (Test-Path -LiteralPath $full) {
        if (-not (Test-Path -LiteralPath $full -PathType Container) -or (Get-ChildItem -LiteralPath $full -Force | Select-Object -First 1)) { throw 'OutputDirectory must be new or empty so evidence cannot include stale files.' }
    } else { New-Item -ItemType Directory -Path $full | Out-Null }
    return $full
}
function Assert-RootedNonReparseDirectory([string]$Path,[string]$Name) {
    if(-not [IO.Path]::IsPathRooted($Path) -or -not(Test-Path -LiteralPath $Path -PathType Container)){throw "$Name must be an existing explicit rooted directory."}
    $resolved=(Resolve-Path -LiteralPath $Path).Path; $ancestor=$resolved
    while($true){$item=Get-Item -LiteralPath $ancestor -Force;if(($item.Attributes -band [IO.FileAttributes]::ReparsePoint) -ne 0){throw "$Name or an ancestor is a reparse-point: $ancestor"};$parent=Split-Path -Parent $ancestor;if([string]::IsNullOrWhiteSpace($parent) -or $parent -eq $ancestor){break};$ancestor=$parent}
    return $resolved
}
function Require-Tool([string]$Path, [string]$Name, [string]$Root) {
    if (-not [IO.Path]::IsPathRooted($Path) -or -not (Test-Path -LiteralPath $Path -PathType Leaf)) { throw "$Name must be an existing explicit rooted path." }
    $resolved = (Resolve-Path -LiteralPath $Path).Path; $root = (Resolve-Path -LiteralPath $Root).Path.TrimEnd('\','/')
    if (-not $resolved.StartsWith("$root\", [StringComparison]::OrdinalIgnoreCase)) { throw "$Name must resolve beneath RuntimeRoot. PATH fallback is prohibited." }
    return $resolved
}
function Normalize-RelativePath([string]$Path, [string]$Description) {
    if ([string]::IsNullOrWhiteSpace($Path) -or [IO.Path]::IsPathRooted($Path)) { throw "$Description contains an unsafe path." }
    $normalized = $Path.Replace('\','/'); $segments = $normalized.Split('/')
    if (@($segments | Where-Object { $_ -in @('', '.', '..') }).Count) { throw "$Description contains an unsafe path." }
    return $normalized
}
function Assert-ContainedFixture([string]$RelativePath) {
    $relative = Normalize-RelativePath $RelativePath 'Fixture path'; $root = [IO.Path]::GetFullPath($fixtures).TrimEnd('\','/')
    $candidate = [IO.Path]::GetFullPath((Join-Path $root $relative.Replace('/', [IO.Path]::DirectorySeparatorChar)))
    if (-not $candidate.StartsWith("$root$([IO.Path]::DirectorySeparatorChar)", [StringComparison]::OrdinalIgnoreCase)) { throw 'Fixture path contains an unsafe path.' }
    $current = $root
    if (((Get-Item -LiteralPath $current -Force).Attributes -band [IO.FileAttributes]::ReparsePoint) -ne 0) { throw 'FixtureRoot must not be a reparse-point.' }
    foreach ($segment in $relative.Split('/')) { $current=Join-Path $current $segment; if (-not (Test-Path -LiteralPath $current)) { throw "Fixture is missing: $relative" }; if (((Get-Item -LiteralPath $current -Force).Attributes -band [IO.FileAttributes]::ReparsePoint) -ne 0) { throw "Fixture path contains a reparse-point: $relative" } }
    if (-not (Test-Path -LiteralPath $candidate -PathType Leaf)) { throw "Fixture is not a file: $relative" }
    return $candidate
}
function Test-Fixtures() {
    $reportPath=Join-Path $fixtures 'generated-fixture-report.json'; $inventoryPath=Join-Path $PSScriptRoot 'fixture-source-inventory.json'
    if (-not (Test-Path -LiteralPath $reportPath) -or -not (Test-Path -LiteralPath $inventoryPath)) { throw 'Fixture report and checked-in fixture source inventory are required.' }
    try { $report=Get-Content -LiteralPath $reportPath -Raw | ConvertFrom-Json; $inventory=Get-Content -LiteralPath $inventoryPath -Raw | ConvertFrom-Json } catch { throw 'Fixture report is truncated or invalid JSON.' }
    $inventoryHash=(Get-FileHash -LiteralPath $inventoryPath -Algorithm SHA256).Hash.ToUpperInvariant()
    if ($report.profileId -ne 'P2.BtbnLgplShared.WindowsX64.20260820' -or $report.externalMediaCommandsExecuted -or $report.approvedInventory.path -ne 'eng/gate0/fixture-source-inventory.json' -or $report.approvedInventory.sha256 -ne $inventoryHash) { throw 'Fixture report approved inventory does not match the checked-in fixture source inventory.' }
    $expected=@{};$reported=@{};$actual=@{}
    foreach($entry in @($inventory.files)) { $path=Normalize-RelativePath ([string]$entry.path) 'Inventory path';if($expected.ContainsKey($path) -or [int64]$entry.length -lt 0 -or ([string]$entry.sha256)-notmatch '^[A-F0-9]{64}$'){throw "Fixture inventory entry is invalid: $path"};$expected[$path]=$entry }
    foreach($entry in @($report.sourceFiles)) { $path=Normalize-RelativePath ([string]$entry.path) 'Fixture report path';if($reported.ContainsKey($path) -or [int64]$entry.length -lt 0 -or ([string]$entry.sha256)-notmatch '^[A-F0-9]{64}$'){throw "Fixture report entry is invalid: $path"};$reported[$path]=$entry }
    foreach($item in @(Get-ChildItem -LiteralPath $fixtures -File -Recurse -Force)){if(($item.Attributes -band [IO.FileAttributes]::ReparsePoint)-ne 0){throw "Fixture actual file is a reparse-point: $($item.FullName)"};$path=Normalize-RelativePath ([IO.Path]::GetRelativePath($fixtures,$item.FullName).Replace('\','/')) 'Fixture actual path';if($path -ne 'generated-fixture-report.json'){$actual[$path]=[ordered]@{length=$item.Length;sha256=(Get-FileHash -LiteralPath $item.FullName -Algorithm SHA256).Hash.ToUpperInvariant()}}}
    foreach($item in @(Get-ChildItem -LiteralPath $fixtures -Directory -Recurse -Force)){if(($item.Attributes -band [IO.FileAttributes]::ReparsePoint)-ne 0){throw "Fixture actual directory is a reparse-point: $($item.FullName)"}}
    foreach($path in @($expected.Keys+$reported.Keys+$actual.Keys|Select-Object -Unique)){if(-not $expected.ContainsKey($path)-or-not $reported.ContainsKey($path)-or-not $actual.ContainsKey($path)){throw "Fixture report/inventory/actual-root file set differs: $path"};foreach($candidate in @($reported[$path],$actual[$path])){if([int64]$candidate.length -ne [int64]$expected[$path].length -or ([string]$candidate.sha256).ToUpperInvariant() -ne ([string]$expected[$path].sha256).ToUpperInvariant()){throw "Fixture report hash or length mismatch: $path"}}}
    return [ordered]@{ reportSha256=(Get-FileHash -LiteralPath $reportPath -Algorithm SHA256).Hash.ToUpperInvariant(); inventorySha256=$inventoryHash; report=$report }
}
function Route-Components([object]$Capability) { $route=$Capability.route; $video=$route.PSObject.Properties['videoEncoder'];$audio=$route.PSObject.Properties['audioEncoder'];return [ordered]@{ inputDemuxers=@($route.inputDemuxers); inputDecoders=@($route.inputDecoders); filters=@($route.filters); streamSelectors=@($route.streamSelectors); videoEncoder=if($null -eq $video){$null}else{$video.Value}; audioEncoder=if($null -eq $audio){$null}else{$audio.Value}; muxer=$route.muxer; outputDemuxer=$route.outputDemuxer; outputDecoders=@($route.outputDecoders) } }
function Command-Components([object]$Capability,[string]$OutputMuxerToken,[string]$ProbeDemuxerToken,[string]$DecodeDemuxerToken){return [ordered]@{fixtureId=$Capability.fixture;runtimeProfileId=$contract.profileId;runtimeIdentityEvidence='runtime-identity.json';dependencyIdentityReference='runtime-identity.json';dependencyIdentitySha256=$runtimeIdentitySha256;inputDemuxerTokens=@($Capability.route.inputDemuxers);inputDecoderTokens=@($Capability.route.inputDecoders);filterTokens=@($Capability.route.filters);streamSelectors=@($Capability.route.streamSelectors);videoEncoderToken=(Get-OptionalProperty $Capability.route 'videoEncoder');audioEncoderToken=(Get-OptionalProperty $Capability.route 'audioEncoder');outputMuxerToken=$OutputMuxerToken;probeDemuxerToken=$ProbeDemuxerToken;decodeDemuxerToken=$DecodeDemuxerToken;outputDecoderTokens=@($Capability.route.outputDecoders);contractRoute=(Route-Components $Capability)}}
function Get-OptionalProperty([object]$Object,[string]$Name){$property=$Object.PSObject.Properties[$Name];if($null -eq $property){return $null};return $property.Value}
function Invoke-Tool([string]$Tool,[string[]]$Arguments,[string]$Step) {
    $stdout=Join-Path $logs "$Step.stdout.txt"; $stderr=Join-Path $logs "$Step.stderr.txt"; & $Tool @Arguments 1>$stdout 2>$stderr
    $record=[ordered]@{step=$Step; executable=$Tool; arguments=$Arguments; exitCode=$LASTEXITCODE; stdout=(Get-Content $stdout -Raw); stderr=(Get-Content $stderr -Raw)}; $commands.Add($record)
    if($LASTEXITCODE -ne 0){ throw "Step '$Step' failed with exit code $LASTEXITCODE." }; return $record
}
function New-AtomicMedia([string]$Name,[string[]]$Arguments) {
    $final=Join-Path $media $Name; $partial=Join-Path $media ('.partial-'+$Name); Invoke-Tool $ffmpeg ($Arguments+@('-y',$partial)) "encode-$Name"|Out-Null
    if(-not(Test-Path -LiteralPath $partial -PathType Leaf) -or (Get-Item -LiteralPath $partial).Length -le 0){throw "Atomic output '$Name' was not created or is empty."}; Move-Item -LiteralPath $partial -Destination $final; return $final
}
function Probe([string]$Path,[string]$Format,[string]$Name) { $record = Invoke-Tool $ffprobe @('-v','error','-f',$Format,'-show_streams','-show_format','-of','json',$Path) "probe-$Name"; return ($record.stdout | ConvertFrom-Json) }
function Decode([string]$Path,[string]$Format,[string]$Decoder,[string]$Selector,[string]$Name,[string]$OutputFormat,[string]$PixelFormat='') {
    $out=Join-Path $work "$Name.raw"; $args=@('-v','error','-f',$Format,'-c:a',$Decoder,'-i',$Path,'-map',$Selector,'-vn')
    if($Selector.StartsWith('0:v')) { $args=@('-v','error','-f',$Format,'-c:v',$Decoder,'-i',$Path,'-map',$Selector,'-an','-c:v','rawvideo'); if($PixelFormat){$args+=@('-pix_fmt',$PixelFormat)} }
    $args+=@('-f',$OutputFormat,'-y',$out); Invoke-Tool $ffmpeg $args "decode-$Name"|Out-Null; return $out
}
function Get-PpmRgb([string]$Path) { $bytes=[IO.File]::ReadAllBytes($Path); $offset=0;$tokens=[Collections.Generic.List[string]]::new(); while($tokens.Count -lt 4){while($offset -lt $bytes.Length -and $bytes[$offset] -in 9,10,13,32){$offset++};$start=$offset;while($offset -lt $bytes.Length -and $bytes[$offset] -notin 9,10,13,32){$offset++};$tokens.Add([Text.Encoding]::ASCII.GetString($bytes,$start,$offset-$start))}; if($tokens[0] -ne 'P6' -or $tokens[1] -ne '320' -or $tokens[2] -ne '180' -or $tokens[3] -ne '255'){throw 'PPM fixture geometry oracle failed.'}; while($offset -lt $bytes.Length -and $bytes[$offset] -in 9,10,13,32){$offset++}; return $bytes[$offset..($bytes.Length-1)] }
function Get-Mae([byte[]]$Expected,[byte[]]$Actual) { if($Expected.Length -ne $Actual.Length){throw 'Visual oracle has incompatible byte lengths.'};[double]$sum=0;for($i=0;$i -lt $Expected.Length;$i++){$sum+=[math]::Abs([int]$Expected[$i]-[int]$Actual[$i])};return $sum/$Expected.Length }
function Test-BytesEqual([byte[]]$Expected,[byte[]]$Actual){if($Expected.Length -ne $Actual.Length){return $false};for($i=0;$i -lt $Expected.Length;$i++){if($Expected[$i] -ne $Actual[$i]){return $false}};return $true}
function Assert-ContainerDuration([object]$Probe,[double]$ExpectedMilliseconds,[double]$ToleranceMilliseconds,[string]$Name){$observed=[double]$Probe.format.duration*1000;if([math]::Abs($observed-$ExpectedMilliseconds)-gt$ToleranceMilliseconds){throw "$Name container-duration oracle failed: expected $ExpectedMilliseconds ms +/- $ToleranceMilliseconds ms, observed $observed ms."};return [ordered]@{expectedMilliseconds=$ExpectedMilliseconds;observedMilliseconds=$observed;toleranceMilliseconds=$ToleranceMilliseconds;passed=$true}}
function Assert-Video([string]$Path,[string]$Format,[string]$ExpectedVideoCodec,[bool]$ExpectAudio,[string]$Name,[string]$ExpectedAudioCodec='',[double]$ExpectedDurationMilliseconds=120,[double]$DurationToleranceMilliseconds=60) {
    $p=Probe $Path $Format $Name; $streams=@($p.streams);$video=@($streams | Where-Object { $_.codec_type -eq 'video' });$audioStreams=@($streams | Where-Object { $_.codec_type -eq 'audio' });if(@($video).Count -ne 1 -or @($audioStreams).Count -ne $(if($ExpectAudio){1}else{0})){throw "$Name stream-layout oracle failed."};if($video[0].codec_name -ne $ExpectedVideoCodec){throw "$Name video codec oracle failed: expected $ExpectedVideoCodec, observed $($video[0].codec_name)."};if($video[0].width -ne 320 -or $video[0].height -ne 180 -or $video[0].avg_frame_rate -ne '25/1'){throw "$Name video structure oracle failed."};if($ExpectAudio -and ($audioStreams[0].codec_name -ne $ExpectedAudioCodec -or $audioStreams[0].sample_rate -ne '48000' -or $audioStreams[0].channels -ne 2)){throw "$Name paired-audio codec/structure oracle failed."};if($ExpectAudio -and $ExpectedAudioCodec -eq 'aac' -and $audioStreams[0].profile -ne 'LC'){throw "$Name AAC-LC profile oracle failed."};$duration=Assert-ContainerDuration $p $ExpectedDurationMilliseconds $DurationToleranceMilliseconds $Name;$decoded=Decode $Path $Format $ExpectedVideoCodec '0:v:0' "$Name-video" 'rawvideo' 'rgb24';$raw=[IO.File]::ReadAllBytes($decoded);$frameBytes=172800;if($raw.Length -ne (3*$frameBytes)){throw "$Name frame-count oracle failed."};$expected=@((Get-PpmRgb (Assert-ContainedFixture 'F1/f1-pattern-000.ppm')),(Get-PpmRgb (Assert-ContainedFixture 'F1/f1-pattern-001.ppm')),(Get-PpmRgb (Assert-ContainedFixture 'F1/f1-pattern-002.ppm')));$maes=@();for($f=0;$f -lt 3;$f++){$actual=$raw[($f*$frameBytes)..((($f+1)*$frameBytes)-1)];$matching=Get-Mae $expected[$f] $actual;$others=@(0..2 | Where-Object {$_ -ne $f} | ForEach-Object {Get-Mae $expected[$_] $actual});if($matching -gt 18 -or $matching -ge ($others|Measure-Object -Minimum).Minimum){throw "$Name presentation-order/frame identity oracle failed."};$maes+=$matching};$audioEvidence=$null;if($ExpectAudio){$audioRaw=Decode $Path $Format $ExpectedAudioCodec '0:a:0' "$Name-audio" 's16le';$audioEvidence=Assert-F1Audio ([IO.File]::ReadAllBytes($audioRaw)) $Name;$audioEvidence.decoder=$ExpectedAudioCodec};return [ordered]@{streamMap=@($streams | ForEach-Object {"$($_.index):$($_.codec_type):$($_.codec_name):$(Get-OptionalProperty $_ 'profile')"});expectedVideoCodec=$ExpectedVideoCodec;expectedAudioCodec=$ExpectedAudioCodec;observedVideoProfile=(Get-OptionalProperty $video[0] 'profile');observedVideoLevel=(Get-OptionalProperty $video[0] 'level');containerDuration=$duration;meanAbsoluteErrors=$maes;pairedAudio=$audioEvidence;probe=$p}
}
function Read-BeUInt32([byte[]]$Bytes,[int]$Offset){return ([uint32]$Bytes[$Offset] -shl 24) -bor ([uint32]$Bytes[$Offset+1] -shl 16) -bor ([uint32]$Bytes[$Offset+2] -shl 8) -bor [uint32]$Bytes[$Offset+3]}
function Assert-Mp4Atoms([string]$Path) {$b=[IO.File]::ReadAllBytes($Path);$offset=0;$boxes=[Collections.Generic.List[object]]::new();while($offset -lt $b.Length){if($b.Length-$offset -lt 8){throw 'MP4 top-level box oracle failed: truncated header.'};$size=[uint64](Read-BeUInt32 $b $offset);$type=[Text.Encoding]::ASCII.GetString($b,$offset+4,4);$header=8;if($size -eq 1){if($b.Length-$offset -lt 16){throw 'MP4 top-level box oracle failed: truncated extended size.'};$size=0;for($i=0;$i -lt 8;$i++){$size=($size -shl 8)-bor $b[$offset+8+$i]};$header=16}elseif($size -eq 0){$size=[uint64]($b.Length-$offset)};if($size -lt $header -or $size -gt [uint64]($b.Length-$offset)){throw 'MP4 top-level box oracle failed: invalid box length.'};$boxes.Add([ordered]@{type=$type;offset=$offset;size=$size});$offset+=[int]$size};$moov=@($boxes|Where-Object type -eq 'moov');$mdat=@($boxes|Where-Object type -eq 'mdat');if($moov.Count -ne 1 -or $mdat.Count -ne 1 -or $moov[0].offset -gt $mdat[0].offset){throw 'MP4 faststart oracle failed: a top-level moov box must precede mdat.'};return [ordered]@{topLevelBoxes=$boxes;moovOffset=$moov[0].offset;mdatOffset=$mdat[0].offset}}
function Read-EbmlVint([byte[]]$Bytes,[int]$Offset,[bool]$Id){if($Offset -ge $Bytes.Length){throw 'WebM EBML oracle failed: truncated VINT.'};$first=$Bytes[$Offset];$length=1;while($length -le 8 -and ($first -band (0x80 -shr ($length-1))) -eq 0){$length++};if($length -gt 8 -or $Offset+$length -gt $Bytes.Length){throw 'WebM EBML oracle failed: invalid VINT.'};[uint64]$value=if($Id){$first}else{$first -band (0x7f -shr ($length-1))};for($i=1;$i -lt $length;$i++){$value=($value -shl 8)-bor $Bytes[$Offset+$i]};$unknown=$false;if(-not $Id){$unknown=$value -eq (([uint64]1 -shl (7*$length))-1)};return [ordered]@{length=$length;value=$value;unknown=$unknown}}
function Assert-WebmCues([string]$Path){$b=[IO.File]::ReadAllBytes($Path);$offset=0;$segmentEnd=$null;$cues=$null;while($offset -lt $b.Length){$id=Read-EbmlVint $b $offset $true;$size=Read-EbmlVint $b ($offset+$id.length) $false;$data=$offset+$id.length+$size.length;if($data -gt $b.Length){throw 'WebM EBML oracle failed: element data starts beyond file.'};[uint64]$end=if($size.unknown){$b.Length}else{$data+$size.value};if($end -gt $b.Length){throw 'WebM EBML oracle failed: element exceeds file.'};if($id.value -eq 0x18538067){$segmentEnd=$end;$child=$data;while($child -lt $segmentEnd){$childId=Read-EbmlVint $b $child $true;$childSize=Read-EbmlVint $b ($child+$childId.length) $false;$childData=$child+$childId.length+$childSize.length;[uint64]$childEnd=if($childSize.unknown){$segmentEnd}else{$childData+$childSize.value};if($childData -gt $segmentEnd -or $childEnd -gt $segmentEnd){throw 'WebM EBML oracle failed: bounded Segment child exceeds Segment.'};if($childId.value -eq 0x1C53BB6B){$cues=[ordered]@{offset=$child;size=$childSize.value;end=$childEnd};break};$child=[int]$childEnd};break};$offset=[int]$end};if($null -eq $cues){throw 'WebM Cues oracle failed: bounded Segment-level Cues element is absent.'};return [ordered]@{cuesOffset=$cues.offset;cuesEnd=$cues.end;segmentEnd=$segmentEnd}}
function Get-TonePower([byte[]]$Bytes,[int]$Frequency,[int]$Channel){$samples=$Bytes.Length/4;if($samples -lt 100){throw 'Audio oracle input is too short.'};[double]$re=0;[double]$im=0;for($n=0;$n -lt $samples;$n++){[int16]$v=[BitConverter]::ToInt16($Bytes,(($n*2+$Channel)*2));$a=2*[math]::PI*$Frequency*$n/48000;$re+=$v*[math]::Cos($a);$im-=$v*[math]::Sin($a)};return $re*$re+$im*$im}
function Get-ChannelPhaseCorrelation([byte[]]$Bytes){$samples=$Bytes.Length/4;[double]$dot=0;[double]$left=0;[double]$right=0;for($n=0;$n -lt $samples;$n++){[double]$l=[BitConverter]::ToInt16($Bytes,$n*4);[double]$r=[BitConverter]::ToInt16($Bytes,$n*4+2);$dot+=$l*$r;$left+=$l*$l;$right+=$r*$r};if($left -eq 0 -or $right -eq 0){throw 'Audio phase oracle input is silent.'};return $dot/[math]::Sqrt($left*$right)}
function Assert-F1Audio([byte[]]$Bytes,[string]$Name){$samples=$Bytes.Length/4;if([math]::Abs($samples-5760)-gt3072){throw "$Name paired-audio sample-count oracle failed."};$l440=Get-TonePower $Bytes 440 0;$l880=Get-TonePower $Bytes 880 0;$r440=Get-TonePower $Bytes 440 1;$r880=Get-TonePower $Bytes 880 1;if($l440 -le $l880 -or $r880 -le $r440){throw "$Name paired-audio channel/tone oracle failed: F1 requires left 440 Hz and right 880 Hz."};return [ordered]@{decodedSamplesPerChannel=$samples;left440Power=$l440;left880Power=$l880;right440Power=$r440;right880Power=$r880;semantics='F1 left=440 Hz; right=880 Hz'} }
function Assert-Audio([string]$Path,[string]$Format,[string]$ExpectedCodec,[bool]$Lossless,[string]$Name,[double]$ExpectedDurationMilliseconds=500,[double]$DurationToleranceMilliseconds=60){$p=Probe $Path $Format $Name;$s=@($p.streams | Where-Object { $_.codec_type -eq 'audio' });if(@($s).Count -ne 1 -or $s[0].codec_name -ne $ExpectedCodec -or $s[0].sample_rate -ne '48000' -or $s[0].channels -ne 2){throw "$Name audio codec/stream-layout oracle failed."};if($ExpectedCodec -eq 'aac' -and $s[0].profile -ne 'LC'){throw "$Name standalone AAC-LC profile oracle failed."};$duration=Assert-ContainerDuration $p $ExpectedDurationMilliseconds $DurationToleranceMilliseconds $Name;$decoded=Decode $Path $Format $ExpectedCodec '0:a:0' "$Name-audio" 's16le';$bytes=[IO.File]::ReadAllBytes($decoded);$source=[IO.File]::ReadAllBytes((Assert-ContainedFixture 'F4/f4-stereo-48000-1000hz-opposed.pcm'));if($Lossless){if(-not(Test-BytesEqual $source $bytes)){throw "$Name lossless PCM oracle failed."}}else{$samples=$bytes.Length/4;if([math]::Abs($samples-24000) -gt 3072){throw "$Name codec-delay-aware sample oracle failed."};$left=Get-TonePower $bytes 1000 0;$right=Get-TonePower $bytes 1000 1;$comparison=@(500,750,1250,1500)|ForEach-Object{[math]::Max((Get-TonePower $bytes $_ 0),(Get-TonePower $bytes $_ 1))};if($left -le ($comparison|Measure-Object -Maximum).Maximum -or $right -le ($comparison|Measure-Object -Maximum).Maximum){throw "$Name stereo-tone oracle failed."};$phase=Get-ChannelPhaseCorrelation $bytes;if($phase -gt -0.60){throw "$Name opposed-phase oracle failed: F4 requires opposed stereo phase."}};return [ordered]@{expectedCodec=$ExpectedCodec;decodedSamplesPerChannel=($bytes.Length/4);containerDuration=$duration;streamMap=@($s | ForEach-Object {"$($_.index):$($_.codec_name):$(Get-OptionalProperty $_ 'profile')"});opposedPhaseCorrelation=if($Lossless){Get-ChannelPhaseCorrelation $bytes}else{$phase}}}
function Assert-ImageStream([string]$Path,[string]$ExpectedCodec,[string]$Name){$p=Probe $Path 'image2' $Name;$streams=@($p.streams|Where-Object codec_type -eq 'video');if($streams.Count -ne 1 -or $streams[0].codec_name -ne $ExpectedCodec -or $streams[0].width -ne 320 -or $streams[0].height -ne 180){throw "$Name image codec/structure oracle failed."};return [ordered]@{expectedCodec=$ExpectedCodec;observedCodec=$streams[0].codec_name;width=$streams[0].width;height=$streams[0].height}}
function Artifact([string]$Path){$item=Get-Item -LiteralPath $Path;return [ordered]@{path=[IO.Path]::GetRelativePath($output,$item.FullName).Replace('\','/');length=$item.Length;sha256=(Get-FileHash -LiteralPath $item.FullName -Algorithm SHA256).Hash.ToUpperInvariant()}}
function Write-Proof([string]$Id,[string]$Status,[string]$Summary,[int]$Start,[object]$Details){$capability=@($contract.capabilities|Where-Object id -eq $Id)[0];$proof=[ordered]@{schemaVersion=1;capabilityId=$Id;fixtureId=$capability.fixture;runtimeProfileId=$contract.profileId;runtimeIdentityEvidence='runtime-identity.json';dependencyIdentityReference='runtime-identity.json';dependencyIdentitySha256=$runtimeIdentitySha256;status=$Status;executedSemanticProof=($Status -eq 'passed');summary=$Summary;commands=@($commands|Select-Object -Skip $Start);details=$Details};[IO.File]::WriteAllText((Join-Path $proofDirectory (($Id.Replace('.','-'))+'.json')),($proof|ConvertTo-Json -Depth 30),[Text.UTF8Encoding]::new($false));$proofs.Add($proof)}
function Classify([Exception]$Exception) { if ($Exception.Message -match 'oracle') { return 'invalid-oracle' }; return 'execution-failed' }

$output=Require-OutsideRepositoryEmptyDirectory $OutputDirectory
$commands=[Collections.Generic.List[object]]::new();$proofs=[Collections.Generic.List[object]]::new();$active=$null;$preflight=[ordered]@{status='started';failure=$null};$preflightComplete=$false
trap { $caught=$_;$ready=Get-Variable -Name preflightComplete -ValueOnly -ErrorAction SilentlyContinue;$target=Get-Variable -Name output -ValueOnly -ErrorAction SilentlyContinue;if($ready -ne $true -and -not [string]::IsNullOrWhiteSpace($target)){$preflight.status='failed';$preflight.failure=$caught.Exception.Message;$record=[ordered]@{schemaVersion=1;profileId='P2.BtbnLgplShared.WindowsX64.20260820';preflight=$preflight;semanticProofs=@();commands=@();finalArtifacts=@()};[IO.File]::WriteAllText((Join-Path $target 'g0.4-delivery-proof-evidence.json'),($record|ConvertTo-Json -Depth 12),[Text.UTF8Encoding]::new($false))};throw $caught }
$runtime=Assert-RootedNonReparseDirectory $RuntimeRoot 'RuntimeRoot';$fixtures=Assert-RootedNonReparseDirectory $FixtureRoot 'FixtureRoot';$ffmpeg=Require-Tool (Join-Path $runtime 'bin\ffmpeg.exe') 'ffmpeg.exe' $runtime;$ffprobe=Require-Tool (Join-Path $runtime 'bin\ffprobe.exe') 'ffprobe.exe' $runtime
$contract=Get-Content -LiteralPath (Join-Path $PSScriptRoot 'g0.4-delivery-proof-contract.json') -Raw|ConvertFrom-Json;$media=Join-Path $output 'media';$work=Join-Path $output 'work';$logs=Join-Path $work 'logs';$proofDirectory=Join-Path $output 'capabilities';New-Item -ItemType Directory -Path $media,$work,$logs,$proofDirectory|Out-Null
$identity=Join-Path $output 'runtime-identity.json';& (Join-Path $PSScriptRoot 'Validate-P2Runtime.ps1') -RuntimeRoot $runtime -EvidencePath $identity;if($LASTEXITCODE -ne 0 -or -not(Test-Path -LiteralPath $identity)){throw 'Approved paired runtime identity validation failed; no G0.4 proof was run.'};$runtimeIdentitySha256=(Get-FileHash -LiteralPath $identity -Algorithm SHA256).Hash.ToUpperInvariant();$fixtureValidation=Test-Fixtures;$preflight.status='passed';$preflightComplete=$true
$null=Assert-ContainedFixture 'F1/f1-pattern-000.ppm';$null=Assert-ContainedFixture 'F1/f1-pattern-001.ppm';$null=Assert-ContainedFixture 'F1/f1-pattern-002.ppm';$f1Pattern=Join-Path $fixtures 'F1\f1-pattern-%03d.ppm';$f1Audio=Assert-ContainedFixture 'F1/f1-sync-440hz-880hz-48000-stereo.pcm';$f4=Assert-ContainedFixture 'F4/f4-stereo-48000-1000hz-opposed.pcm'
$videoInput=@('-hide_banner','-framerate','25','-start_number','0','-f','image2','-c:v','ppm','-i',$f1Pattern,'-f','s16le','-c:a','pcm_s16le','-ar','48000','-ac','2','-i',$f1Audio,'-map','0:v:0','-map','1:a:0','-shortest')
$videoOnlyInput=@('-hide_banner','-framerate','25','-start_number','0','-f','image2','-c:v','ppm','-i',$f1Pattern,'-map','0:v:0')
try {
  $start=$commands.Count;$active=$contract.capabilities[0];$path=New-AtomicMedia 'p2-openh264-aac.mp4' ($videoInput+@('-vf','format=yuv420p','-c:v','libopenh264','-profile:v','constrained_baseline','-rc_mode','bitrate','-b:v','2M','-g','25','-allow_skip_frames','false','-c:a','aac','-profile:a','aac_low','-b:a','192k','-movflags','+faststart','-f','mp4'));$details=Assert-Video $path 'mp4' 'h264' $true 'openh264-aac' 'aac' ([double]$contract.oracles.audio.f1DurationMilliseconds) ([double]$contract.oracles.audio.compressedContainerDurationToleranceMilliseconds);$details.mp4=Assert-Mp4Atoms $path;Write-Proof $active.id 'passed' 'Explicit libopenh264 plus native AAC MP4 A/V proof passed; OpenH264 profile/rate-control warnings remain recorded quality-policy evidence.' $start ([ordered]@{artifact=(Artifact $path);componentSelection=(Command-Components $active 'mp4' 'mp4' 'mp4');requestedVideoProfile='constrained_baseline';requestedRateControl='bitrate at 2M with frame skipping disabled';unresolvedQualityPolicyEvidence='OpenH264 initialization warnings are preserved in the command stderr. Observed stream profile/level are separate from requested encoder options.';oracle=$details})
  $start=$commands.Count;$active=$contract.capabilities[1];$path=New-AtomicMedia 'p2-openh264-video-only.mp4' ($videoOnlyInput+@('-an','-vf','format=yuv420p','-c:v','libopenh264','-profile:v','constrained_baseline','-rc_mode','bitrate','-b:v','2M','-g','25','-allow_skip_frames','false','-movflags','+faststart','-f','mp4'));$details=Assert-Video $path 'mp4' 'h264' $false 'openh264-video-only' '' ([double]$contract.oracles.audio.f1DurationMilliseconds) ([double]$contract.oracles.audio.compressedContainerDurationToleranceMilliseconds);$details.mp4=Assert-Mp4Atoms $path;Write-Proof $active.id 'passed' 'Explicit libopenh264 MP4 video-only proof passed; warnings remain recorded as unresolved quality-policy evidence.' $start @{artifact=(Artifact $path);componentSelection=(Command-Components $active 'mp4' 'mp4' 'mp4');requestedVideoProfile='constrained_baseline';requestedRateControl='bitrate at 2M with frame skipping disabled';unresolvedQualityPolicyEvidence='See recorded encoder stderr.';oracle=$details}
  $start=$commands.Count;$active=$contract.capabilities[2];$path=New-AtomicMedia 'vp9-opus.webm' ($videoInput+@('-vf','format=yuv420p','-c:v','libvpx-vp9','-b:v','0','-crf','32','-g','25','-deadline','good','-cpu-used','2','-row-mt','0','-threads','1','-c:a','libopus','-b:a','128k','-vbr','off','-compression_level','10','-frame_duration','20','-f','webm'));$details=Assert-Video $path 'webm' 'vp9' $true 'vp9-opus' 'opus' ([double]$contract.oracles.audio.f1DurationMilliseconds) ([double]$contract.oracles.audio.compressedContainerDurationToleranceMilliseconds);$details.webm=Assert-WebmCues $path;Write-Proof $active.id 'passed' 'Explicit VP9/Opus WebM A/V proof passed.' $start @{artifact=(Artifact $path);componentSelection=(Command-Components $active 'webm' 'webm' 'webm');oracle=$details}
  $start=$commands.Count;$active=$contract.capabilities[3];$path=New-AtomicMedia 'vp9-video-only.webm' ($videoOnlyInput+@('-an','-vf','format=yuv420p','-c:v','libvpx-vp9','-b:v','0','-crf','32','-g','25','-deadline','good','-cpu-used','2','-row-mt','0','-threads','1','-f','webm'));$details=Assert-Video $path 'webm' 'vp9' $false 'vp9-video-only' '' ([double]$contract.oracles.audio.f1DurationMilliseconds) ([double]$contract.oracles.audio.compressedContainerDurationToleranceMilliseconds);$details.webm=Assert-WebmCues $path;Write-Proof $active.id 'passed' 'Explicit VP9 WebM video-only proof passed.' $start @{artifact=(Artifact $path);componentSelection=(Command-Components $active 'webm' 'webm' 'webm');oracle=$details}
  $audioBase=@('-hide_banner','-f','s16le','-c:a','pcm_s16le','-ar','48000','-ac','2','-i',$f4,'-map','0:a:0')
  $audioSpecs=@(@($contract.capabilities[4],'m4a-aac.m4a','ipod','aac',@('-profile:a','aac_low','-b:a','192k'),$false),@($contract.capabilities[5],'mp3.mp3','mp3','libmp3lame',@('-b:a','192k'),$false),@($contract.capabilities[6],'opus.ogg','ogg','libopus',@('-b:a','128k','-vbr','off','-compression_level','10','-frame_duration','20'),$false),@($contract.capabilities[7],'pcm.wav','wav','pcm_s16le',@('-rf64','never'),$true),@($contract.capabilities[8],'flac.flac','flac','flac',@('-compression_level','5'),$true))
  foreach($spec in $audioSpecs){$start=$commands.Count;$active=$spec[0];$path=New-AtomicMedia $spec[1] ($audioBase+@('-c:a',$spec[3])+$spec[4]+@('-f',$spec[2]));$probeFormat=if($spec[2] -eq 'ipod'){'mp4'}else{$spec[2]};$outputDecoder=[string]$active.route.outputDecoders[0];$durationTolerance=if($spec[5]){[double]$contract.oracles.audio.losslessContainerDurationToleranceMilliseconds}else{[double]$contract.oracles.audio.compressedContainerDurationToleranceMilliseconds};$details=Assert-Audio $path $probeFormat $outputDecoder $spec[5] $spec[1] ([double]$contract.oracles.audio.f4DurationMilliseconds) $durationTolerance;Write-Proof $active.id 'passed' "Explicit $($spec[3]) $($spec[2]) audio proof passed." $start @{artifact=(Artifact $path);componentSelection=(Command-Components $active $spec[2] $probeFormat $probeFormat);oracle=$details}}
  $start=$commands.Count;$active=$contract.capabilities[9];$path=New-AtomicMedia 'frame.png' @('-hide_banner','-f','image2','-c:v','ppm','-i',(Assert-ContainedFixture 'F1/f1-pattern-000.ppm'),'-frames:v','1','-c:v','png','-compression_level','9','-pred','mixed','-update','1','-f','image2');$stream=Assert-ImageStream $path 'png' 'png';$raw=Decode $path 'image2' 'png' '0:v:0' 'png' 'rawvideo' 'rgb24';$expectedPng=Get-PpmRgb (Assert-ContainedFixture 'F1/f1-pattern-000.ppm');$observedPng=[IO.File]::ReadAllBytes($raw);$pngPassed=Test-BytesEqual $expectedPng $observedPng;$pngOracle=[ordered]@{kind='exact-rgb24-pixels';expected=@{byteLength=$expectedPng.Length;sha256=([Convert]::ToHexString([Security.Cryptography.SHA256]::HashData($expectedPng)))};observed=@{byteLength=$observedPng.Length;sha256=([Convert]::ToHexString([Security.Cryptography.SHA256]::HashData($observedPng)))};threshold='exact byte equality';passed=$pngPassed};if(-not $pngPassed){throw 'PNG exact-pixel oracle failed.'};Write-Proof $active.id 'passed' 'Explicit PNG image proof passed with exact decoded RGB pixels.' $start @{artifact=(Artifact $path);componentSelection=(Command-Components $active 'image2' 'image2' 'image2');stream=$stream;oracle=$pngOracle}
  $start=$commands.Count;$active=$contract.capabilities[10];$path=New-AtomicMedia 'frame.jpg' @('-hide_banner','-f','image2','-c:v','ppm','-i',(Assert-ContainedFixture 'F1/f1-pattern-000.ppm'),'-frames:v','1','-vf','format=yuvj420p','-c:v','mjpeg','-q:v','2','-huffman','optimal','-f','image2');$stream=Assert-ImageStream $path 'mjpeg' 'jpeg';$raw=Decode $path 'image2' 'mjpeg' '0:v:0' 'jpeg' 'rawvideo' 'rgb24';$mae=Get-Mae (Get-PpmRgb (Assert-ContainedFixture 'F1/f1-pattern-000.ppm')) ([IO.File]::ReadAllBytes($raw));$jpegOracle=[ordered]@{kind='rgb24-mean-absolute-error';expected=@{maximumMeanAbsoluteError=18};observed=@{meanAbsoluteError=$mae};threshold=18;passed=($mae -le 18)};if(-not $jpegOracle.passed){throw "JPEG visual oracle failed: MAE $mae exceeds 18."};Write-Proof $active.id 'passed' 'Explicit MJPEG/JPEG image proof passed with declared visual tolerance.' $start @{artifact=(Artifact $path);componentSelection=(Command-Components $active 'image2' 'image2' 'image2');stream=$stream;oracle=$jpegOracle}
} catch { if($null -ne $active){Write-Proof $active.id (Classify $_.Exception) $_.Exception.Message $start @{reason='The contract was not weakened to accommodate this result.'}};foreach($cap in @($contract.capabilities) | Where-Object {$_.id -notin @($proofs | ForEach-Object capabilityId)}){Write-Proof $cap.id 'not-run' 'Not run because an earlier active capability failed.' $commands.Count @{blockedBy=$active.id}};throw
} finally {$artifacts=@(Get-ChildItem -LiteralPath $media -File|Sort-Object Name|%{Artifact $_.FullName});$evidence=[ordered]@{schemaVersion=1;profileId=$contract.profileId;contract='eng/gate0/g0.4-delivery-proof-contract.json';preflight=$preflight;runtimeIdentityEvidence='runtime-identity.json';fixtureRoot=$fixtures;fixtureReportVerified=$true;fixtureReportSha256=$fixtureValidation.reportSha256;componentPresence='See runtime-identity.json; presence is not semantic proof.';dependencyIdentity='Exact archive/manifest and validated DLL hash closure are recorded in runtime-identity.json; no unexposed upstream dependency version is claimed.';limitations='Proof-only: not a shipping, distribution, patent, legal, independent-playback, or long-form conclusion.';commands=$commands;finalArtifacts=$artifacts;semanticProofs=$proofs};[IO.File]::WriteAllText((Join-Path $output 'g0.4-delivery-proof-evidence.json'),($evidence|ConvertTo-Json -Depth 40),[Text.UTF8Encoding]::new($false))}
