[CmdletBinding()]
param(
    [Parameter(Mandatory)][string] $ArtifactRoot,
    [Parameter(Mandatory)][string] $FfmpegPath,
    [Parameter(Mandatory)][string] $FfprobePath,
    [Parameter(Mandatory)][string] $OutputDirectory
)

Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'

# Proof-only retained-corpus evaluator. It never re-encodes route outputs, does
# not select a shipping runtime, and makes no product, distribution, or quality
# claim beyond the frozen technical oracle.
$repositoryRoot=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..')).TrimEnd('\','/')
$groupId='Gate0.G05.Calibration.20260826T004152697Z.FDABDAA2'
$freezePath=Join-Path $PSScriptRoot 'g0.5-lossy-audio-oracle-freeze.json'
$retentionValidator=Join-Path $PSScriptRoot 'Test-Gate0ArtifactRetention.ps1'
$controlsPath=Join-Path $PSScriptRoot 'Invoke-G05LossyAudioOracleControls.ps1'
$helperPath=Join-Path $PSScriptRoot 'G05RetainedAudioOracleHelpers.psm1'
Import-Module $helperPath -Force
function Hash([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToUpperInvariant()}
function Atomic([string]$Path,$Value){$partial="$Path.partial";try{[IO.File]::WriteAllText($partial,($Value|ConvertTo-Json -Depth 100),[Text.UTF8Encoding]::new($false));Move-Item -LiteralPath $partial -Destination $Path -Force}finally{if(Test-Path $partial){Remove-Item $partial -Force}}}
function Assert-Directory([string]$Path,[string]$Name,[bool]$Exists=$true){if(-not[IO.Path]::IsPathRooted($Path)){throw "$Name must be absolute."};$full=[IO.Path]::GetFullPath($Path).TrimEnd('\','/');$boundary=[IO.Path]::GetDirectoryName($repositoryRoot).TrimEnd('\','/');if(-not$full.StartsWith("$boundary\",[StringComparison]::OrdinalIgnoreCase)){throw "$Name is outside the approved project-parent trust boundary."};if($Exists-and-not(Test-Path -LiteralPath $full -PathType Container)){throw "$Name must be an existing directory."};$walk=if(Test-Path $full){Get-Item -LiteralPath $full -Force}else{Get-Item -LiteralPath ([IO.Path]::GetDirectoryName($full)) -Force};while($null-ne$walk){if(($walk.Attributes-band[IO.FileAttributes]::ReparsePoint)-ne0){throw "$Name traverses a reparse-point."};if($walk.FullName.TrimEnd('\','/').Equals($boundary,[StringComparison]::OrdinalIgnoreCase)){break};$walk=$walk.Parent};if(Test-Path $full){foreach($item in @(Get-ChildItem $full -Force -Recurse)){if(($item.Attributes-band[IO.FileAttributes]::ReparsePoint)-ne0){throw "$Name contains a reparse-point."}}};$full}
function Assert-File([string]$Path,[string]$Root,[string]$Name){if(-not[IO.Path]::IsPathRooted($Path)-or-not(Test-Path -LiteralPath $Path -PathType Leaf)){throw "$Name must be an existing absolute file."};$file=(Resolve-Path -LiteralPath $Path).Path;$root=(Resolve-Path -LiteralPath $Root).Path.TrimEnd('\','/');if(-not$file.StartsWith("$root\",[StringComparison]::OrdinalIgnoreCase)){throw "$Name must resolve beneath the approved P2 artifact root; PATH discovery is prohibited."};if((Get-Item $file -Force).Attributes-band[IO.FileAttributes]::ReparsePoint){throw "$Name is a reparse-point."};$file}
function Retained([string]$Relative){if([IO.Path]::IsPathRooted($Relative)-or$Relative.Contains('..')){throw 'Unsafe retained relative path.'};$path=[IO.Path]::GetFullPath((Join-Path $artifact $Relative.Replace('/','\')));if(-not$path.StartsWith("$artifact\",[StringComparison]::OrdinalIgnoreCase)-or-not(Test-Path $path -PathType Leaf)){throw "Retained file missing or escaped: $Relative"};$path}
function Run([string]$Exe,[string[]]$Arguments,[string]$Name){$stdout=Join-Path $logs "$Name.stdout.txt";$stderr=Join-Path $logs "$Name.stderr.txt";& $Exe @Arguments 1>$stdout 2>$stderr;[ordered]@{executable=$Exe;arguments=$Arguments;exitCode=$LASTEXITCODE;stdout=[ordered]@{path=("logs/"+[IO.Path]::GetFileName($stdout));size=(Get-Item $stdout).Length;sha256=(Hash $stdout)};stderr=[ordered]@{path=("logs/"+[IO.Path]::GetFileName($stderr));size=(Get-Item $stderr).Length;sha256=(Hash $stderr)}}}

$out=$null;$state=[ordered]@{schemaVersion=1;proofId='Gate0.G05.RetainedAudioOracle.V1';groupId=$groupId;status='started';routeReencodePerformed=$false;thresholdSelectionReadOutputs=$false;expectedRows=48;evaluatedRows=0;rows=@();routeDispositions=@();nonClaims=@('No perceptual-transparency claim.','No shipping-runtime, distribution, patent, or legal conclusion.');error=$null}
try {
    $artifact=Assert-Directory $ArtifactRoot 'ArtifactRoot';$approved=Join-Path ([IO.Path]::GetDirectoryName($repositoryRoot)) 'ReelForge.Gate0Artifacts';if(-not$artifact.Equals($approved,[StringComparison]::OrdinalIgnoreCase)){throw "ArtifactRoot must be the exact approved repository sibling: $approved"}
    $out=Assert-Directory $OutputDirectory 'OutputDirectory' $false;$staging=Join-Path ([IO.Path]::GetDirectoryName($repositoryRoot)) 'ReelForge.Gate0Staging';if([IO.Path]::GetDirectoryName($out)-ne$staging){throw "OutputDirectory must be a new direct child beneath approved staging root: $staging"};if(Test-Path $out){throw 'OutputDirectory must be a new absolute directory.'};[IO.Directory]::CreateDirectory($out)|Out-Null;$logs=Join-Path $out 'logs';$decoded=Join-Path $out 'decoded';$controls=Join-Path $out 'controls';@($logs,$decoded)|%{[IO.Directory]::CreateDirectory($_)|Out-Null}
    $state.localCorpusPreflight=& $retentionValidator -ArtifactRoot $artifact
    $ffmpeg=Assert-File $FfmpegPath $artifact 'FfmpegPath';$ffprobe=Assert-File $FfprobePath $artifact 'FfprobePath';$p2Relative='p2/runtime/ffmpeg-n8.1.2-44-g7c533d0f86-win64-lgpl-shared-8.1/bin';$expectedFfmpeg=[IO.Path]::GetFullPath((Join-Path $artifact "$p2Relative/ffmpeg.exe"));$expectedFfprobe=[IO.Path]::GetFullPath((Join-Path $artifact "$p2Relative/ffprobe.exe"));if(-not$ffmpeg.Equals($expectedFfmpeg,[StringComparison]::OrdinalIgnoreCase)-or-not$ffprobe.Equals($expectedFfprobe,[StringComparison]::OrdinalIgnoreCase)){throw 'FfmpegPath and FfprobePath must equal the exact approved P2 relative paths.'}
    $freeze=Get-Content $freezePath -Raw|ConvertFrom-Json -Depth 32;foreach($f in @($freeze.frozenFiles)){$p=Join-Path $repositoryRoot $f.path;if(-not(Test-Path $p)-or(Get-Item $p).Length-ne[int64]$f.size-or(Hash $p)-ne$f.sha256){throw "Frozen file verification failed: $($f.path)"}}
    $manifest=Get-Content (Join-Path $PSScriptRoot 'artifact-retention-manifest.json') -Raw|ConvertFrom-Json -Depth 64;$group=@($manifest.groups|Where-Object groupId -eq $groupId);if($group.Count-ne1){throw 'Exact retained calibration group was not found.'};$media=@($group[0].files|Where-Object{$_.filename-match'/media/.+\.(mp4|webm)$'});if($media.Count-ne48){throw "Expected exactly 48 retained media artifacts, found $($media.Count)."};$evidenceEntry=@($group[0].files|Where-Object{$_.filename-match'/g0.5-calibration-evidence\.json$'});if($evidenceEntry.Count-ne1){throw 'Retained Stage 1 evidence declaration is missing or ambiguous.'};$evidencePath=Retained $evidenceEntry[0].filename;if((Get-Item $evidencePath).Length-ne[int64]$evidenceEntry[0].size-or(Hash $evidencePath)-ne$evidenceEntry[0].sha256){throw 'Retained Stage 1 evidence manifest size/SHA verification failed.'};$stage1=Get-Content $evidencePath -Raw|ConvertFrom-Json -Depth 100;Assert-G05Stage1Matrix @($stage1.attempts);$state.stage1Evidence=[ordered]@{path=$evidenceEntry[0].filename;size=$evidenceEntry[0].size;sha256=$evidenceEntry[0].sha256;attemptCount=@($stage1.attempts).Count}
    $source=Retained 'fixtures/F1/f1-sync-440hz-880hz-48000-stereo.pcm';if((Hash $source)-ne'D6D0E575C834A0BFCF442713745EC409CC0774BF4D9356DA0B68A07D3F3F0E78'){throw 'F1 source PCM hash mismatch.'}
    # Invoke the hash-pinned frozen script in this process; it defines the only
    # approved Analyze implementation and reruns all 12 frozen controls.
    if('ReelForge.Gate0.LossyAudioControls'-as[type]){throw 'Frozen controls type was already loaded before approved frozen-script invocation.'};& $controlsPath -ReferencePcmPath $source -OutputDirectory $controls | Out-Null;if(-not('ReelForge.Gate0.LossyAudioControls'-as[type])){throw 'Frozen lossy-audio controls did not load or pass.'};$controlReport=Join-Path $controls 'g0.5-lossy-audio-control-results.json';if((Hash $controlReport)-ne$freeze.controlEvidence.sha256){throw 'Frozen control evidence hash mismatch.'};$reference=[ReelForge.Gate0.LossyAudioControls]::MakeReference([IO.File]::ReadAllBytes($source));$referenceBytes=[byte[]]::new($reference.Length*2);[Buffer]::BlockCopy($reference,0,$referenceBytes,0,$referenceBytes.Length);$referenceHash=([Security.Cryptography.SHA256]::HashData($referenceBytes)|ForEach-Object ToString x2)-join'';if($referenceHash.ToUpperInvariant() -ne '3A9BF240990CB5EC08026C83D6E2FC64A95011C8D35D2B2B7FECFF55B91639EA'){throw 'Regenerated 8-second reference hash mismatch.'}
    foreach($entry in $media){
        $record=[ordered]@{artifact=$entry.filename;status='started';failures=@();originalAttempt=$null;command=$null;timing=$null;quality=$null};$state.rows+=,$record
        try {
            $mediaPath=Retained $entry.filename;if((Get-Item $mediaPath).Length-ne[int64]$entry.size-or(Hash $mediaPath)-ne$entry.sha256){throw 'Retained media identity mismatch.'};$mediaName=[IO.Path]::GetFileName($mediaPath)
            $matches=@($stage1.attempts|Where-Object{$null-ne$_.command-and([IO.Path]::GetFileName([string]$_.command.arguments[-1]))-eq$mediaName});if($matches.Count-ne1){throw 'Retained media artifact must bind to exactly one original Stage 1 attempt output command path.'};$attempt=$matches[0]
            $record.originalAttempt=[ordered]@{routeId=$attempt.row.routeId;resolutionId=$attempt.row.resolutionId;threadPolicyId=$attempt.row.threadPolicyId;repetitionKind=$attempt.row.repetitionKind;repetitionOrdinal=$attempt.row.repetitionOrdinal;command=$attempt.command}
            $isMp4=$attempt.row.routeId-eq'Video.Export.Compatibility.Mp4H264Aac.P2OpenH264';$expectedExtension=if($isMp4){'.mp4'}else{'.webm'};if(-not$mediaName.EndsWith($expectedExtension)){throw 'Retained extension/container does not match original route.'};if($attempt.measurement.exitCode-ne0){throw 'Original FFmpeg attempt did not exit zero.'}
            if($attempt.oracle-and$attempt.oracle.artifactSha256){if($attempt.oracle.artifactSha256-ne$entry.sha256){throw 'Original oracle artifact hash does not match retained manifest.'};$oracleHashDisposition='matched-original-oracle'}elseif($isMp4-and$attempt.status-eq'failed'-and([string]$attempt.error)-match'Audio waveform oracle failed'){$oracleHashDisposition='unavailable-old-aac-oracle-threw-before-recording-manifest-hash-verified'}else{throw 'Original attempt artifact hash is absent without the exact retained AAC old-oracle failure disposition.'}
            $demuxer=if($isMp4){'mov,mp4,m4a,3gp,3g2,mj2'}else{'matroska,webm'};$decoder=if($isMp4){'aac'}else{'opus'};$id=[IO.Path]::GetFileNameWithoutExtension($mediaPath);$raw=Join-Path $decoded "$id.s16le"
            $probe=Run -Exe $ffprobe -Arguments @('-v','error','-f',$demuxer,'-show_streams','-show_packets','-show_frames','-show_format','-of','json',$mediaPath) -Name "probe-$id";$record.command=[ordered]@{probe=$probe;decode=$null;demuxer=$demuxer;decoder=$decoder;map='0:a:0';routeReencodePerformed=$false;oracleArtifactHashDisposition=$oracleHashDisposition}
            if($probe.exitCode-ne0){throw 'Probe command failed.'};$probeStdout=Join-Path $logs "probe-$id.stdout.txt";$probeJson=Get-Content $probeStdout -Raw|ConvertFrom-Json;$audio=@($probeJson.streams|? codec_type -eq 'audio');if($audio.Count-ne1-or$audio[0].codec_name-ne$decoder-or$audio[0].sample_rate-ne'48000'-or[int]$audio[0].channels-ne2){throw 'Audio stream identity gate failed.'}
            $decode=Run -Exe $ffmpeg -Arguments @('-v','error','-f',$demuxer,'-c:a',$decoder,'-i',$mediaPath,'-map','0:a:0','-vn','-c:a','pcm_s16le','-f','s16le','-y',$raw) -Name "decode-$id";$record.command.decode=$decode;if($decode.exitCode-ne0){$record.partialDecode=if(Test-Path $raw){[ordered]@{path=("decoded/"+[IO.Path]::GetFileName($raw));size=(Get-Item $raw).Length;sha256=(Hash $raw)}}else{$null};throw 'Decode command failed.'}
            $bytes=[IO.File]::ReadAllBytes($raw);if($bytes.Length%4-ne0){$record.failures+=,'decoded-byte-length-not-stereo-s16le-aligned'};$samples=[int]($bytes.Length/4);$timing=Get-G05AudioTiming $audio[0] @($probeJson.packets|? codec_type -eq 'audio') @($probeJson.frames|? media_type -eq 'audio') $samples;if(-not$timing.timingPassed){$record.failures+=@($timing.failures)}
            $rawHash=Hash $raw;$record.timing=[ordered]@{rawPcm=[ordered]@{path=("decoded/"+[IO.Path]::GetFileName($raw));size=$bytes.Length;sha256=$rawHash};normalizedPcm=[ordered]@{path=("decoded/"+[IO.Path]::GetFileName($raw));size=$bytes.Length;sha256=$rawHash};selectedAudioStream=$audio[0];firstPacket=@($probeJson.packets|? codec_type -eq 'audio'|Select-Object -First 1);finalPacket=@($probeJson.packets|? codec_type -eq 'audio'|Select-Object -Last 1);firstFrame=@($probeJson.frames|? media_type -eq 'audio'|Select-Object -First 1);finalFrame=@($probeJson.frames|? media_type -eq 'audio'|Select-Object -Last 1);timing=$timing}
            $actual=[int16[]]::new($bytes.Length/2);[Buffer]::BlockCopy($bytes,0,$actual,0,$bytes.Length);$metrics=[ReelForge.Gate0.LossyAudioControls]::Analyze($reference,$actual);if(-not$metrics.Passed){$record.failures+=@($metrics.Failures)};$record.quality=$metrics;$record.status=if($record.failures.Count){'failed'}else{'passed'}
        }catch{$record.status='failed';$record.failures+=,$_.Exception.Message};$state.evaluatedRows++
    }
    foreach($route in @('Video.Export.Compatibility.Mp4H264Aac.P2OpenH264','Video.Export.Open.WebmVp9Opus')){$rows=@($state.rows|? {$_.originalAttempt.routeId-eq$route});$state.routeDispositions+=,[ordered]@{routeId=$route;admitted=($rows.Count-eq24-and@($rows|? status -eq 'passed').Count-eq24);expected=24;passed=@($rows|? status -eq 'passed').Count;failed=@($rows|? status -ne 'passed').Count;disposition=if(@($rows|? status -ne 'passed').Count){'blocked'}else{'admitted'}}};$state.status=if(@($state.rows|? status -ne 'passed').Count){'completed-with-failures'}else{'completed'}
}catch{$state.status='infrastructure-failed';$state.error=$_.Exception.ToString()}finally{if($out-and(Test-Path $out)){Atomic (Join-Path $out 'g0.5-retained-audio-oracle-report.json') $state};$state|ConvertTo-Json -Depth 100;if($state.status-eq'infrastructure-failed'){exit 1};if($state.status-eq'completed-with-failures'){exit 2}}
