[CmdletBinding()]
param([Parameter(Mandatory)][string]$ControlReportPath,[Parameter(Mandatory)][string]$FreezeCandidatePath,[Parameter(Mandatory)][string]$V4AuthoritativeControlReportPath,[Parameter(Mandatory)][string]$OutputPath)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
function Hash([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToUpperInvariant()}
function Assert-ExactIdSet([hashtable]$Expected,[hashtable]$Actual,[string]$Label){if($Expected.Count -ne $Actual.Count -or @($Expected.Keys|Where-Object{$_ -notin $Actual.Keys}).Count -or @($Actual.Keys|Where-Object{$_ -notin $Expected.Keys}).Count){throw "$Label identifier set is not exact."}}
foreach($path in @($ControlReportPath,$FreezeCandidatePath,$V4AuthoritativeControlReportPath)){if(-not [IO.Path]::IsPathRooted($path) -or -not (Test-Path -LiteralPath $path -PathType Leaf)){throw 'Freeze inputs must be existing absolute files.'}}
if(-not [IO.Path]::IsPathRooted($OutputPath) -or (Test-Path -LiteralPath $OutputPath)){throw 'OutputPath must be an absolute new file.'}
$report=Get-Content $ControlReportPath -Raw|ConvertFrom-Json -Depth 64;$candidate=Get-Content $FreezeCandidatePath -Raw|ConvertFrom-Json -Depth 64
if($report.status -ne 'passed-controls-only-freeze-candidate-pending' -or $candidate.status -ne 'controls-passed-freeze-candidate-not-frozen' -or $candidate.controlReport.sha256 -ne (Hash $ControlReportPath)){throw 'V5 controls have not passed into the exact freeze candidate.'}
if($report.amendmentId -ne 'Gate0.G05.LossyAudioOracle.V5.ReferenceRelativeStress.20260827' -or $report.legacyV3Controls.count -ne 12 -or $report.legacyV4Controls.count -ne 5 -or -not $report.legacyV3Controls.exactBidirectionalIdSetPreserved -or -not $report.legacyV4Controls.exactBidirectionalIdSetPreserved -or -not $report.legacyV3Controls.allFrozenDispositionsAndHashesPreserved -or -not $report.legacyV4Controls.allFrozenDispositionsAndHashesPreserved){throw 'V5 control closure is incomplete.'}
if($report.routeOutputsEvaluated -or $report.routeReencodePerformed -or $report.retainedMp4OrWebmOutputsRead -or $report.executionBoundary.ffmpegInvoked -or $report.executionBoundary.ffprobeInvoked -or $report.executionBoundary.mediaProcessesStarted -or $report.executionBoundary.retainedCodecOutputsRead){throw 'V5 control execution boundary is widened.'}
$v5Expected=@{'stress-identity'=$true;'stress-gain-95-percent'=$true;'stress-right-low-level-960-sample-dropout'=$false;'stress-gain-75-percent'=$false;'stress-gain-125-percent'=$false};$v5Actual=@{};foreach($control in @($report.structuredControls)){if($v5Actual.ContainsKey([string]$control.id)){throw 'Duplicate V5 structured control identifier.'};$v5Actual[[string]$control.id]=$control};Assert-ExactIdSet $v5Expected $v5Actual 'V5 structured control';foreach($id in $v5Expected.Keys){$control=$v5Actual[$id];if([bool]$control.expectedPass -ne [bool]$v5Expected[$id] -or [bool]$control.actualPass -ne [bool]$v5Expected[$id]){throw 'V5 structured control disposition changed.'}};if(-not(@($v5Actual['stress-right-low-level-960-sample-dropout'].result.failures)-match'reference-relative-window-rms-ratio')){throw 'V5 dropout did not fail through the required reference-relative-window-rms-ratio.'}
$canonical=@{'eng/gate0/g0.5-lossy-audio-oracle-contract.json'='119A4C179BFA010F3202DBF6AA368E42EDE5FD0FC23EF2781AA9C7F63540CBE4';'eng/gate0/g0.5-lossy-audio-oracle-amendment-v4.json'='21ECAFCD94F71E58AA43955079EF9959C135DB12530D015E8380CFD09B5E9FBC';'eng/gate0/g0.5-lossy-audio-oracle-amendment-v4-freeze.json'='E2EFFD683FFE21BE902D77D7564F81C550F555C0989871C5D98B2DBE580D4CB2';'eng/gate0/g0.5-structured-audio-control-result-summary.json'='83097DA638B80D048F84CC86B29BB24463C0B2BF9C2D3ED78CAF658FC73BF5EE'}
$expectedInputPaths=@('eng/gate0/g0.5-lossy-audio-oracle-contract.json','eng/gate0/g0.5-lossy-audio-oracle-amendment-v4.json','eng/gate0/g0.5-lossy-audio-oracle-amendment-v4-freeze.json','eng/gate0/g0.5-lossy-audio-oracle-amendment-v5.json','eng/gate0/g0.5-stage2-workload-contract.json','eng/gate0/G05Stage2SmokeHelpers.psm1','eng/gate0/G05Stage2ASemanticHelpers.psm1','eng/gate0/G05Stage2AV5AudioOracle.psm1','eng/gate0/Invoke-G05LossyAudioOracleControls.ps1','eng/gate0/Invoke-G05StructuredAudioOracleControls.ps1','eng/gate0/g0.5-structured-audio-control-result-summary.json','eng/gate0/Invoke-G05Stage2AV5AudioOracleControls.ps1','eng/gate0/New-G05Stage2AV5AudioOracleFreeze.ps1','eng/gate0/artifact-retention-manifest.json');$actualInputs=@{};foreach($entry in @($candidate.frozenInputs)){if($actualInputs.ContainsKey([string]$entry.path)){throw 'Duplicate V5 frozen input path.'};$actualInputs[[string]$entry.path]=$entry};$inputSet=@{};foreach($path in $expectedInputPaths){$inputSet[$path]=$true};Assert-ExactIdSet $inputSet $actualInputs 'V5 frozen input';foreach($path in $expectedInputPaths){$local=Join-Path $PSScriptRoot ([IO.Path]::GetFileName($path));if(-not(Test-Path -LiteralPath $local -PathType Leaf) -or (Hash $local) -ne [string]$actualInputs[$path].sha256){throw 'V5 frozen input no longer matches its exact candidate hash.'};if($canonical.ContainsKey($path) -and [string]$actualInputs[$path].sha256 -ne $canonical[$path]){throw 'Canonical inherited V3/V4 input hash changed.'}}
if($candidate.authoritativeV4ControlReport.groupId -ne 'G05-V4-Structured-Audio-Controls-20260827-001' -or $candidate.authoritativeV4ControlReport.artifactId -ne 'G05-V4-Structured-Audio-Controls-20260827-001/g0.5-structured-audio-oracle-control-results.json' -or $candidate.authoritativeV4ControlReport.filename -ne 'g0.5/v4-structured-audio-controls/20260827-001/g0.5-structured-audio-oracle-control-results.json' -or (Hash $V4AuthoritativeControlReportPath) -ne '2CAEE1C652F292BBF7E9DB6E1DAA0DD7C5E68788C3E5D74F63997DC3775F2AF6' -or [string]$candidate.authoritativeV4ControlReport.sha256 -ne '2CAEE1C652F292BBF7E9DB6E1DAA0DD7C5E68788C3E5D74F63997DC3775F2AF6'){throw 'Authoritative retained V4 report byte binding changed.'}
$overlay=$candidate.amendment.overlay;if($candidate.amendment.amendmentId -ne 'Gate0.G05.LossyAudioOracle.V5.ReferenceRelativeStress.20260827' -or $candidate.amendment.status -ne 'owner-approved-controls-required-before-retained-output-reevaluation' -or @($candidate.amendment.referenceDescriptorIds).Count -ne 1 -or [string]$candidate.amendment.referenceDescriptorIds[0] -ne 'stress-4v8a-30s' -or $overlay.referenceDescriptorId -ne 'stress-4v8a-30s' -or $overlay.mode -ne 'reference-relative-active-windows-v1' -or [int]$overlay.windowSamples -ne 960 -or [double]$overlay.minimumOutputToReferenceRmsRatio -ne 0.90 -or [double]$overlay.maximumOutputToReferenceRmsRatio -ne 1.10){throw 'V5 amendment scope or overlay is not exact.'};$checks=@($overlay.replacesV3Checks|Sort-Object -Unique);$requiredChecks=@('qualityThresholds.minimumActiveChannelRmsFullScale','qualityThresholds.minimumActiveReferenceWindowOutputRmsFullScale');if($checks.Count -ne 2 -or @($checks|Where-Object{$_ -notin $requiredChecks}).Count -or @($requiredChecks|Where-Object{$_ -notin $checks}).Count){throw 'V5 amendment replacement set is not exact.'}
$freeze=[ordered]@{schemaVersion=1;freezeId='Gate0.G05.LossyAudioOracle.V5.ReferenceRelativeStress.Frozen.20260827';status='frozen-after-controls-passed-before-retained-output-reevaluation';frozenUtc=[DateTimeOffset]::UtcNow.ToString('O');controlReport=[ordered]@{path=[IO.Path]::GetFileName($ControlReportPath);sha256=(Hash $ControlReportPath);size=(Get-Item $ControlReportPath).Length};freezeCandidate=[ordered]@{path=[IO.Path]::GetFileName($FreezeCandidatePath);sha256=(Hash $FreezeCandidatePath);size=(Get-Item $FreezeCandidatePath).Length};frozenInputs=@($candidate.frozenInputs);authoritativeV4ControlReport=$candidate.authoritativeV4ControlReport;retainedOutputEvaluationAuthorized=$false;routeReencodeAuthorized=$false};[IO.File]::WriteAllText($OutputPath,($freeze|ConvertTo-Json -Depth 64),[Text.UTF8Encoding]::new($false));$freeze|ConvertTo-Json -Depth 64
