using ReelForge.Application;
using ReelForge.Core;
using ReelForge.Infrastructure;

namespace ReelForge.Tests;

public sealed class PortableProjectCloneFileSystemTests : IDisposable
{
    private readonly string _root = Path.Combine(Path.GetTempPath(), "ReelForge tests", Guid.NewGuid().ToString("N"));

    [Fact]
    public async Task StagingCopiesDurableProjectFilesButExcludesCacheRecoveryProjectAndTemporaryFiles()
    {
        var source = await CreateSourceAsync();
        await WriteFileAsync(source.Root, "assets/videos/source.mp4", "video bytes");
        await WriteFileAsync(source.Root, "generated/retained.mp4", "generated bytes");
        await WriteFileAsync(source.Root, "custom/metadata.txt", "durable metadata");
        Directory.CreateDirectory(Path.Combine(source.Root, "assets", "images"));
        Directory.CreateDirectory(Path.Combine(source.Root, "exports"));
        var staleStaging = Directory.CreateDirectory(Path.Combine(
            source.Root,
            ".Old copy.clone-0123456789abcdef0123456789abcdef")).FullName;
        await File.WriteAllTextAsync(Path.Combine(staleStaging, "Old copy.rfp"), "unpublished clone");
        await WriteFileAsync(source.Root, "cache/preview.mp4", "cache bytes");
        await File.WriteAllTextAsync(PortableProjectStore.GetRecoveryFilePath(source.Location), "recovery");
        await WriteFileAsync(source.Root, ".Source.rfp.project-save-0123456789abcdef0123456789abcdef.tmp", "temporary");
        await WriteFileAsync(source.Root, ".reelforge-rename-0123456789abcdef0123456789abcdef.mp4", "rename temporary");

        var progress = new List<ProjectCloneProgress>();
        var cloneFileSystem = new PortableProjectCloneFileSystem();
        var staging = await cloneFileSystem.StageDurableContentAsync(
            source.Location,
            _root,
            "Clone",
            new CallbackProgress<ProjectCloneProgress>(progress.Add),
            CancellationToken.None);

        Assert.True(File.Exists(Path.Combine(staging.StagingLocation.RootDirectory, "assets", "videos", "source.mp4")));
        Assert.True(File.Exists(Path.Combine(staging.StagingLocation.RootDirectory, "generated", "retained.mp4")));
        Assert.True(File.Exists(Path.Combine(staging.StagingLocation.RootDirectory, "custom", "metadata.txt")));
        Assert.True(Directory.Exists(Path.Combine(staging.StagingLocation.RootDirectory, "assets", "images")));
        Assert.True(Directory.Exists(Path.Combine(staging.StagingLocation.RootDirectory, "exports")));
        Assert.Equal(
            await File.ReadAllTextAsync(Path.Combine(source.Root, "assets", "videos", "source.mp4")),
            await File.ReadAllTextAsync(Path.Combine(staging.StagingLocation.RootDirectory, "assets", "videos", "source.mp4")));
        Assert.False(Directory.Exists(Path.Combine(staging.StagingLocation.RootDirectory, "cache")));
        Assert.False(Directory.Exists(Path.Combine(staging.StagingLocation.RootDirectory,
            ".Old copy.clone-0123456789abcdef0123456789abcdef")));
        Assert.False(File.Exists(staging.StagingLocation.ProjectFilePath));
        Assert.False(File.Exists(PortableProjectStore.GetRecoveryFilePath(staging.StagingLocation)));
        Assert.False(File.Exists(Path.Combine(staging.StagingLocation.RootDirectory,
            ".Source.rfp.project-save-0123456789abcdef0123456789abcdef.tmp")));
        Assert.Contains(progress, update => update.Phase == ProjectClonePhase.Scanning && update.TotalFileCount == 3);
        Assert.Contains(progress, update => update.Phase == ProjectClonePhase.Copying &&
                                            update.CopiedFileCount == 3 && update.CopiedBytes == update.TotalBytes);

        await cloneFileSystem.RollbackAsync(staging);

        Assert.False(Directory.Exists(staging.StagingLocation.RootDirectory));
        Assert.True(File.Exists(source.Location.ProjectFilePath));
        Assert.True(File.Exists(Path.Combine(source.Root, "cache", "preview.mp4")));
    }

    [Fact]
    public async Task PublishAtomicallyMovesOwnedStagingDirectoryToRequestedProjectFolder()
    {
        var source = await CreateSourceAsync();
        await WriteFileAsync(source.Root, "assets/audio/voice.m4a", "audio bytes");
        var cloneFileSystem = new PortableProjectCloneFileSystem();

        var staging = await cloneFileSystem.StageDurableContentAsync(
            source.Location, _root, "Published", null, CancellationToken.None);

        await cloneFileSystem.PublishAsync(staging, CancellationToken.None);

        Assert.False(Directory.Exists(staging.StagingLocation.RootDirectory));
        Assert.True(Directory.Exists(staging.FinalLocation.RootDirectory));
        Assert.Equal(Path.Combine(_root, "Published", "Published.rfp"), staging.FinalLocation.ProjectFilePath);
        Assert.True(File.Exists(Path.Combine(staging.FinalLocation.RootDirectory, "assets", "audio", "voice.m4a")));

        await Assert.ThrowsAsync<IOException>(() => cloneFileSystem.StageDurableContentAsync(
            source.Location, _root, "Published", null, CancellationToken.None));
    }

    [Fact]
    public async Task CancellationDuringCopyRemovesOwnedStagingDirectoryAndDoesNotPublishClone()
    {
        var source = await CreateSourceAsync();
        await WriteBytesAsync(source.Root, "assets/videos/large.mp4", new byte[256 * 1024]);
        using var cancellation = new CancellationTokenSource();
        var progress = new CallbackProgress<ProjectCloneProgress>(update =>
        {
            if (update.Phase == ProjectClonePhase.Copying && update.CopiedBytes > 0)
                cancellation.Cancel();
        });
        var cloneFileSystem = new PortableProjectCloneFileSystem();

        await Assert.ThrowsAnyAsync<OperationCanceledException>(() => cloneFileSystem.StageDurableContentAsync(
            source.Location, _root, "Cancelled", progress, cancellation.Token));

        Assert.False(Directory.Exists(Path.Combine(_root, "Cancelled")));
        Assert.Empty(Directory.EnumerateDirectories(_root, ".Cancelled.clone-*", SearchOption.TopDirectoryOnly));
    }

    [Fact]
    public async Task RejectsCloneDestinationInsideSourceProject()
    {
        var source = await CreateSourceAsync();
        var destinationInsideSource = Path.Combine(source.Root, "clones");
        Directory.CreateDirectory(destinationInsideSource);

        var exception = await Assert.ThrowsAsync<InvalidOperationException>(() =>
            new PortableProjectCloneFileSystem().StageDurableContentAsync(
                source.Location, destinationInsideSource, "Nested", null, CancellationToken.None));

        Assert.Contains("outside the source", exception.Message, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public async Task CloneServicePublishesReopenableProjectAndPreservesInternalGraph()
    {
        var store = new PortableProjectStore();
        var sourceRoot = Path.Combine(_root, "Real source");
        var (source, sourceLocation) = await store.CreateAsync(sourceRoot, "Original");
        var physical = new ProjectAsset
        {
            DisplayName = "Source clip",
            FileName = "source.mp4",
            MediaType = MediaType.Video,
            StorageKind = AssetStorageKind.Physical,
            Physical = new PhysicalAssetStorage
            {
                RelativePath = "assets/videos/source.mp4",
                ContentIdentity = new ContentIdentity
                {
                    Sha256 = new string('a', 64),
                    Status = ContentHashStatus.Verified,
                    LengthBytes = 12
                }
            },
            ProviderReferences = new Dictionary<string, ProviderAssetReference>(StringComparer.Ordinal)
            {
                ["fake"] = new() { Value = "provider-history", SourceContentHash = new string('a', 64) }
            }
        };
        var savedClip = new ProjectAsset
        {
            DisplayName = "Saved clip",
            FileName = "saved-clip.mp4",
            MediaType = MediaType.Video,
            StorageKind = AssetStorageKind.Virtual,
            Origin = AssetOrigin.EditorDerived,
            Physical = null,
            Virtual = new VirtualAssetState { Kind = VirtualAssetKind.SavedClip }
        };
        source.AddAsset(physical);
        source.AddAsset(savedClip);
        var revision = source.CommitRecipe(savedClip.Id, new TrimRecipe
        {
            Source = new AssetRevisionReference { AssetId = physical.Id },
            Start = RecipeBoundary.SourceStart,
            End = RecipeBoundary.SourceEnd
        });
        var sourceMediaPath = Path.Combine(sourceRoot, "assets", "videos", "source.mp4");
        await File.WriteAllTextAsync(sourceMediaPath, "durable bytes");
        await store.SaveAsync(source, sourceLocation);
        await File.WriteAllTextAsync(PortableProjectStore.GetRecoveryFilePath(sourceLocation), "source recovery");
        await File.WriteAllTextAsync(Path.Combine(sourceRoot, "cache", "preview.bin"), "disposable");
        var committedSourceBytes = await File.ReadAllBytesAsync(sourceLocation.ProjectFilePath);

        var service = new ProjectCloneService(
            store,
            new PortableProjectCloneFileSystem(),
            new ProjectSaveCoordinator());
        var result = await service.CloneAsync(new ProjectCloneRequest(
            sourceLocation.ProjectFilePath,
            _root,
            "Independent copy"));
        var (reopened, reopenedLocation) = await store.OpenAsync(result.Location.ProjectFilePath);

        Assert.NotEqual(source.Id, reopened.Id);
        Assert.Equal("Independent copy", reopened.Name);
        Assert.Equal(physical.Id, reopened.Assets.Single(asset => asset.StorageKind == AssetStorageKind.Physical).Id);
        Assert.Equal(savedClip.Id, reopened.Assets.Single(asset => asset.StorageKind == AssetStorageKind.Virtual).Id);
        Assert.Equal(revision.Id, Assert.Single(reopened.RecipeRevisions).Id);
        Assert.Equal(physical.Id, Assert.IsType<TrimRecipe>(reopened.RecipeRevisions.Single().Recipe).Source.AssetId);
        Assert.Equal("provider-history", reopened.Assets.Single(asset => asset.Id == physical.Id).ProviderReferences["fake"].Value);
        Assert.Equal("durable bytes", await File.ReadAllTextAsync(Path.Combine(
            reopenedLocation.RootDirectory, "assets", "videos", "source.mp4")));
        Assert.False(Directory.Exists(Path.Combine(reopenedLocation.RootDirectory, "cache")));
        Assert.False(File.Exists(PortableProjectStore.GetRecoveryFilePath(reopenedLocation)));
        Assert.Equal(committedSourceBytes, await File.ReadAllBytesAsync(sourceLocation.ProjectFilePath));
        Assert.True(File.Exists(PortableProjectStore.GetRecoveryFilePath(sourceLocation)));
    }

    public void Dispose()
    {
        if (Directory.Exists(_root))
            Directory.Delete(_root, recursive: true);
    }

    private async Task<SourceProject> CreateSourceAsync()
    {
        var root = Path.Combine(_root, "Source");
        Directory.CreateDirectory(root);
        var projectPath = Path.Combine(root, "Source.rfp");
        await File.WriteAllTextAsync(projectPath, "committed project");
        return new SourceProject(root, new ProjectLocation(root, projectPath));
    }

    private static async Task WriteFileAsync(string root, string relativePath, string contents)
    {
        var path = Path.Combine(root, relativePath);
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        await File.WriteAllTextAsync(path, contents);
    }

    private static async Task WriteBytesAsync(string root, string relativePath, byte[] contents)
    {
        var path = Path.Combine(root, relativePath);
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        await File.WriteAllBytesAsync(path, contents);
    }

    private sealed record SourceProject(string Root, ProjectLocation Location);

    private sealed class CallbackProgress<T>(Action<T> report) : IProgress<T>
    {
        public void Report(T value) => report(value);
    }
}
